### ISSUE TITLE
[Feature] 希望可以添加国旗显示

### ISSUE THREAD

**Issue by akiker233** [hamster1963/nezha-dash#10]
![image](https://github.com/user-attachments/assets/b7057bb4-e4b8-4f50-a13e-43767ef91429)
希望可以在这个位置加上国旗

**Comment by hamster1963** [comment]
国旗显示对页面布局影响比较大，因为有许多旧版本的面板对于获取地区信息并不太好，会出现许多机器不显示地区信息的情况，计划把这个作为可选项来启用， 如果有更好的建议欢迎 PR👏。
