### ISSUE TITLE
iOS 书签模式顶栏颜色适配

### ISSUE THREAD

**Issue by zhdsmy** [hamster1963/nezha-dash#100]
又来吹毛求疵了，亮色和暗色模式，可以适配一下顶栏的颜色和下面保持一致么，就是时间和信号那一块的背景颜色

![white](https://github.com/user-attachments/assets/5fcbf40e-e75f-4020-b258-7020d97255ca)

![black](https://github.com/user-attachments/assets/e71f451a-6faa-41e8-96d0-da73c7ee28f8)

**Comment by hamster1963** [comment]
![image](https://github.com/user-attachments/assets/54f2eec5-bb14-4bfc-af8c-2c48d3f11cdc)

已重构背景颜色以解决该问题。
