### ISSUE TITLE
哥哥，好像不显示网络

### ISSUE THREAD

**Issue by onexiaolaji** [hamster1963/nezha-dash#101]
哥哥，好像不显示网络

![image](https://github.com/user-attachments/assets/06a277f4-8d4a-45b0-9f2b-14ca52a917d5)
![image](https://github.com/user-attachments/assets/187d9fea-2a92-4c69-a7a1-3f15073a205b)
https://nezha-dash-teal-eta.vercel.app/

**Comment by hamster1963** [comment]
NEXT_PUBLIC_ShowNetTransfer是在主页显示上下行的参数。

<img width="541" alt="CleanShot 2024-11-02 at 23 49 31@2x" src="https://github.com/user-attachments/assets/b3b997ff-5966-45cd-9561-8802c1a166b9">

至于你说的没有数据，这个页面的数据需要在哪吒面板配置服务进行监控，才会在这个页面获取到数据。
https://github.com/hamster1963/nezha-dash/issues/65#issuecomment-2413025541

**Comment by hamster1963** [comment]
修改环境变量后，需要在vercel点击redeploy，具体可参考如何更新服务的教程。
