### ISSUE TITLE
可不可以加个basepath配置，方便把它和nezha-dashboard的域名放一起

### ISSUE THREAD

**Issue by xuecanlong** [hamster1963/nezha-dash#108]
想要个/dash的basepath 方便把它跟nezha dashboard的域名放一起使用  xxx.com/dash是你这个dash 其他还是nezha-dashboard

nginx配置 
xxx.com/dash --> nezha-dash
xxx.com/--> nezha-dashboard

**Comment by hamster1963** [comment]
需要看看能否作为环境变量动态设置

**Comment by Eyeseas** [comment]
[39ed9f4a867ccc07f03199af9a2aad379d8f50ea](https://github.com/hamster1963/nezha-dash/commit/39ed9f4a867ccc07f03199af9a2aad379d8f50ea)

这么快加上了,厉害!

**Comment by hamster1963** [comment]
已新增，由于 basePath 会在构建时嵌入，因此新增的 basePath 环境变量仅针对 Vercel 与 Cloudflare 环境。

https://nezha-docs.vercel.app/environment#base-path
