### ISSUE TITLE
更新1.4.0后移动端会强制展开分组，拉伸屏幕

### ISSUE THREAD

**Issue by Chilledwatermelon** [hamster1963/nezha-dash#114]
![photo_2024-11-19_23-29-16](https://github.com/user-attachments/assets/28e8ea1a-5de3-4176-9b6d-f95836d2d461)
![photo_2024-11-19_23-29-12](https://github.com/user-attachments/assets/187f0b10-c06c-4441-a50b-2c2b23e6963e)

**Comment by hamster1963** [comment]
正在检查中

**Comment by hamster1963** [comment]
已修复，感谢提出🙏

**Comment by Chilledwatermelon** [comment]
感谢大佬，太迅速辣
