### ISSUE TITLE
开发大大好像并没有完全修复

### ISSUE THREAD

**Issue by Chilledwatermelon** [hamster1963/nezha-dash#115]
![photo_2024-11-19_23-54-43](https://github.com/user-attachments/assets/c11e66bb-b4f1-45a2-8097-6d59f34712a8)

**Comment by hamster1963** [comment]
让我再修修...

**Comment by hamster1963** [comment]
https://github.com/user-attachments/assets/4ee63aaf-1165-4b82-98b2-04111ebd427c

这边好像没有复现这个问题...

**Comment by Chilledwatermelon** [comment]
是不是因为没开，数量显示

**Comment by hamster1963** [comment]
![image](https://github.com/user-attachments/assets/c5d9b144-8683-40fa-9b9c-62261a5649d9)

好像也没有问题..

**Comment by Chilledwatermelon** [comment]
好吧，那我明天再试试

**Comment by hamster1963** [comment]
如暂时没有其他问题，就先关闭这个 issue，可以更新到最新版本后测试
