### ISSUE TITLE
bug: 将地图生成切换到客户端

### ISSUE THREAD

**Issue by hamster1963** [hamster1963/nezha-dash#116]
目前服务端生成 SVG 地图有超出 cloudflare CPU 计算时间的限制，将测试迁移到客户端进行。

**Comment by hamster1963** [comment]
https://github.com/hamster1963/nezha-dash/releases/tag/v1.4.1

已切换为预计算地图

**Comment by zhdsmy** [comment]
地图是个惊喜 feature 呀，👏👏👏，可以点亮整个国家么（单个点不是很明显），右上角还可以显示当前点亮全球百分比（点亮国家数 / 所有国家数）
