### ISSUE TITLE
feat: 世界地图标记点为整个地区

### ISSUE THREAD

**Issue by hamster1963** [hamster1963/nezha-dash#118]
当前，采用平均经纬度进行标记，可采用自定义geo 数据进行完整地区标记。

**Comment by charmingyi** [comment]
> 当前，采用平均经纬度进行标记，可采用自定义geo 数据进行完整地区标记。

我也觉得用点铺满整个地区比较好，可以慢慢点亮全图

**Comment by hamster1963** [comment]
<img width="1118" alt="CleanShot 2024-11-20 at 16 57 15@2x" src="https://github.com/user-attachments/assets/da948ecb-b018-4740-9c3f-1084e5966825">

已基本实现
