### ISSUE TITLE
世界地图中的俄罗斯没有铺满

### ISSUE THREAD

**Issue by FarEastTZ** [hamster1963/nezha-dash#119]
![image](https://github.com/user-attachments/assets/a4503d88-7565-462a-b3cb-ff1a406fc3f4)

**Comment by hamster1963** [comment]
感谢提出，已了解，区域计算算法可能有点问题。

**Comment by hamster1963** [comment]
预计采用人工补全的方式进行修订

**Comment by hamster1963** [comment]
计划重新绘制地图以解决此问题

**Comment by hamster1963** [comment]
<img width="1120" alt="CleanShot 2024-11-21 at 15 21 40@2x" src="https://github.com/user-attachments/assets/f66fd012-fe48-4502-a7a8-ac7243e28ee0">

将在下个版本中修复。
