### ISSUE TITLE
可以改用真实的地图吗？

### ISSUE THREAD

**Issue by autecloud** [hamster1963/nezha-dash#120]
大佬你好，地图感觉有些失真，大小比例感觉有问题！
可以改用真实的地图吗？

**Comment by hamster1963** [comment]
真实地图有类似风格的参考吗？

**Comment by hamster1963** [comment]
目前的地图是参考

![image](https://github.com/user-attachments/assets/c1c72d1b-a330-48ed-8aec-5f05c20d8f94)

请问哪里需要调整呢🤔

**Comment by hamster1963** [comment]
> https://aws.amazon.com/cn/about-aws/global-infrastructure/?p=ngi&loc=0
> 
> 参照下AWS的区域？

现在没有采用投影地图，因此看起来有偏差

**Comment by hamster1963** [comment]
> 目前国家有显示，但是没有互动
> 
> 比如点击后显示在这个国家有哪些服务器？
> 
> 
> 
> 

可能后续会添加，目前地图是服务端渲染的，主要用作展示，暂时不想把功能弄得太复杂

**Comment by dsu-k** [comment]
> > https://aws.amazon.com/cn/about-aws/global-infrastructure/?p=ngi&loc=0
> > 参照下AWS的区域？
> 
> 现在没有采用投影地图，因此看起来有偏差

北半球比例差的有些大，纬度拉伸也有些夸张，可能在web采用WGS84会好点?
![image](https://github.com/user-attachments/assets/acb0ef39-6e04-4fcc-8222-7717bc01b3a7)

**Comment by hamster1963** [comment]
<img width="1134" alt="CleanShot 2024-11-25 at 16 38 07@2x" src="https://github.com/user-attachments/assets/c62a0fe4-7544-4170-890e-31f58b304989">

重写中

**Comment by hamster1963** [comment]
采用版本:
The Equal Eartch projection, by Bojan Šavrič et al., 2018.

**Comment by hamster1963** [comment]
> 目前国家有显示，但是没有互动 比如点击后显示在这个国家有哪些服务器？

<img width="1125" alt="CleanShot 2024-11-25 at 18 01 29@2x" src="https://github.com/user-attachments/assets/ca6da5f3-6189-4c2a-9ab3-b4af32317097">

已增加数量显示

**Comment by hamster1963** [comment]
已在 v1.5.0 中重新实现
