### ISSUE TITLE
cloudflare使用NEXT_PUBLIC_BASE_PATH时的问题

### ISSUE THREAD

**Issue by fx-k** [hamster1963/nezha-dash#122]
在cloudflare设置`NEXT_PUBLIC_BASE_PATH`为`/dash`，部分资源无法加载，首页显示
```
Error status: Unexpected token 'N', "Not Found" is not valid JSON
请检查您的环境变量并检查服务器控制台
Unexpected token 'N', "Not Found" is not valid JSON
请检查您的环境变量并检查服务器控制台
```
F12发现部分资源未正确加载：
例如：`https://ne****g.pages.dev/dash/_next/image?url=%2Fdash%2F_next%2Fstatic%2Fmedia%2Fblog-man.ec59424f.webp&w=3840&q=75`，实测如果去掉/dash/则正常加载。
<img width="574" alt="image" src="https://github.com/user-attachments/assets/ce220d04-a999-441b-bed4-0d025bffd71b">

---
问题应该可以通过下面cloudflare变量复现：
<img width="762" alt="image" src="https://github.com/user-attachments/assets/cb799911-dcce-45c8-8005-002fba25fb85">

**Comment by hamster1963** [comment]
检查修复中

**Comment by hamster1963** [comment]
抱歉，由于目前 basePath 在 authjs 与 nextjs cloudflare-pages 环境下存在 bug，已将此环境变量移除。

**Comment by fx-k** [comment]
抱歉，请问还有办法实现子目录嘛，因为需要跟官方的dashboard共用一个域名。（或者此项目是否有意作为官方的模板进行实现？）

**Comment by hamster1963** [comment]
> 抱歉，请问还有办法实现子目录嘛，因为需要跟官方的dashboard共用一个域名。（或者此项目是否有意作为官方的模板进行实现？）

可关注 1.0 后续公布。
