### ISSUE TITLE
通过Docker安装会出现内存泄露的情况

### ISSUE THREAD

**Issue by whereisxiaobaobei** [hamster1963/nezha-dash#124]
系统Debian 12,通过htop查看到是bun run server.js这个进程发生内存泄露,重新拉取镜像后再启动docker内存占用就会降下来,过一会开始会逐渐升高把内存和swap占满.

# docker logs nezha-dash
▲ Next.js 15.0.3
- Local: http://<container_internal_ip>:3000
- Network: http://<container_network_ip>:3000/
 ✓ Starting...
✓ Ready in 186ms

# docker inspect nezha-dash
[
    {
        "Id": "a8fcccae07231f61bc41da0a08dbf31c3291b6e917715244be9c61b9735c763e",
        "Created": "2024-11-22T14:13:22.255060428Z",
        "Path": "/usr/local/bin/docker-entrypoint.sh",
        "Args": [
            "bun",
            "run",
            "server.js"
        ],
        "State": {
            "Status": "running",
            "Running": true,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 2224,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2024-11-22T14:13:22.752712814Z",
            "FinishedAt": "0001-01-01T00:00:00Z"
        },
        "Image": "sha256:435160a4db9bda96818ebc2a23e6e035654fa3969404dff95b49c817f4b5f40d",
        "ResolvConfPath": "/var/lib/docker/containers/a8fcccae07231f61bc41da0a08dbf31c3291b6e917715244be9c61b9735c763e/resolv.conf",
        "HostnamePath": "/var/lib/docker/containers/a8fcccae07231f61bc41da0a08dbf31c3291b6e917715244be9c61b9735c763e/hostname",
        "HostsPath": "/var/lib/docker/containers/a8fcccae07231f61bc41da0a08dbf31c3291b6e917715244be9c61b9735c763e/hosts",
        "LogPath": "/var/lib/docker/containers/a8fcccae07231f61bc41da0a08dbf31c3291b6e917715244be9c61b9735c763e/a8fcccae07231f61bc41da0a08dbf31c3291b6e917715244be9c61b9735c763e-json.log",
        "Name": "/nezha-dash",
        "RestartCount": 0,
        "Driver": "overlay2",
        "Platform": "linux",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "docker-default",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": [
                "/root/.env:/app/.env:rw"
            ],
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },
            "NetworkMode": "root_default",
            "PortBindings": {
                "3000/tcp": [
                    {
                        "HostIp": "",
                        "HostPort": "4123"
                    }
                ]
            },
            "RestartPolicy": {
                "Name": "always",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": [],
            "CapAdd": null,
            "CapDrop": null,
            "CgroupnsMode": "private",
            "Dns": null,
            "DnsOptions": null,
            "DnsSearch": null,
            "ExtraHosts": null,
            "GroupAdd": null,
            "IpcMode": "private",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": null,
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 67108864,
            "Runtime": "runc",
            "ConsoleSize": [
                0,
                0
            ],
            "Isolation": "",
            "CpuShares": 0,
            "Memory": 0,
            "NanoCpus": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": null,
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": null,
            "DeviceCgroupRules": null,
            "DeviceRequests": null,
            "KernelMemory": 0,
            "KernelMemoryTCP": 0,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": null,
            "OomKillDisable": null,
            "PidsLimit": null,
            "Ulimits": null,
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0,
            "MaskedPaths": [
                "/proc/asound",
                "/proc/acpi",
                "/proc/kcore",
                "/proc/keys",
                "/proc/latency_stats",
                "/proc/timer_list",
                "/proc/timer_stats",
                "/proc/sched_debug",
                "/proc/scsi",
                "/sys/firmware"
            ],
            "ReadonlyPaths": [
                "/proc/bus",
                "/proc/fs",
                "/proc/irq",
                "/proc/sys",
                "/proc/sysrq-trigger"
            ]
        },
        "GraphDriver": {
            "Data": {
                "LowerDir": "/var/lib/docker/overlay2/1bccac6460d2075421cc7acd1353bd953ff89d0a5d36ab8dc2f6abf6e32b669b-init/diff:/var/lib/docker/overlay2/f83b38a03e785548f8f4bd1554e713b796c1001368eae7d149870752413f28f4/diff:/var/lib/docker/overlay2/638567f25e306ee90ff5ae643899a48788c9138470c8a1610890fe13f307cd13/diff:/var/lib/docker/overlay2/3914e24f177a529d4794ae949616667dc9261b3d18561558906dbb48ef323f42/diff:/var/lib/docker/overlay2/533ca683963904a25e82c2371f0f712b443a9d3d77b8e2f28b37e41027a812db/diff:/var/lib/docker/overlay2/581eaea9ec3eaf5982e6b8802525ba4f8f6e828384bf08efb32e7437bdc4ba82/diff:/var/lib/docker/overlay2/0ca83357d0bb3bf47bec865d8a0538ca6378c15dd2e4c9dd6b9fafa1a5333a32/diff:/var/lib/docker/overlay2/deebbf3646fefa8cd0a621942b264be40a749c513cc1abc91f1b9105810b3a5d/diff:/var/lib/docker/overlay2/534cf4be34eef922b204e0fe68f840c340ed9824ce3bce041c2d32ada426c143/diff:/var/lib/docker/overlay2/68e1141408c1b91c36783320ff6da1071f0120e9edcba3457214aded840ddc87/diff",
                "MergedDir": "/var/lib/docker/overlay2/1bccac6460d2075421cc7acd1353bd953ff89d0a5d36ab8dc2f6abf6e32b669b/merged",
                "UpperDir": "/var/lib/docker/overlay2/1bccac6460d2075421cc7acd1353bd953ff89d0a5d36ab8dc2f6abf6e32b669b/diff",
                "WorkDir": "/var/lib/docker/overlay2/1bccac6460d2075421cc7acd1353bd953ff89d0a5d36ab8dc2f6abf6e32b669b/work"
            },
            "Name": "overlay2"
        },
        "Mounts": [
            {
                "Type": "bind",
                "Source": "/root/.env",
                "Destination": "/app/.env",
                "Mode": "rw",
                "RW": true,
                "Propagation": "rprivate"
            }
        ],
        "Config": {
            "Hostname": "a8fcccae0723",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "3000/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "BUN_RUNTIME_TRANSPILER_CACHE_PATH=0",
                "BUN_INSTALL_BIN=/usr/local/bin",
                "NODE_ENV=production"
            ],
            "Cmd": [
                "bun",
                "run",
                "server.js"
            ],
            "Image": "hamster1963/nezha-dash:latest",
            "Volumes": {
                "/app/.env": {}
            },
            "WorkingDir": "/app",
            "Entrypoint": [
                "/usr/local/bin/docker-entrypoint.sh"
            ],
            "OnBuild": null,
            "Labels": {
                "com.docker.compose.config-hash": "4d43d086cd267e2622b4dae7c91cc8ca3908d22088a0f694693d7fe08a6d23c4",
                "com.docker.compose.container-number": "1",
                "com.docker.compose.oneoff": "False",
                "com.docker.compose.project": "root",
                "com.docker.compose.project.config_files": "docker-compose.yml",
                "com.docker.compose.project.working_dir": "/root",
                "com.docker.compose.service": "nezha-dash",
                "com.docker.compose.version": "1.29.2",
                "org.opencontainers.image.created": "2024-11-22T09:59:31.975Z",
                "org.opencontainers.image.description": "A simple dashboard for nezha.",
                "org.opencontainers.image.licenses": "",
                "org.opencontainers.image.revision": "d06e1017d62594a4c2fbdc6d613f184879525a88",
                "org.opencontainers.image.source": "https://github.com/hamster1963/nezha-dash",
                "org.opencontainers.image.title": "nezha-dash",
                "org.opencontainers.image.url": "https://github.com/hamster1963/nezha-dash",
                "org.opencontainers.image.version": "v1.4.7"
            }
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "12119cd345eaf25f24d8119e475e19e75ec4ec8dba8476670f8754b8e6fd19b2",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {
                "3000/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "4123"
                    },
                    {
                        "HostIp": "::",
                        "HostPort": "4123"
                    }
CONTAINER ID   NAME         CPU %     MEM USAGE / LIMIT    MEM %     NET I/O       BLOCK I/O     PIDS
<container_id>   nezha-dash   0.01%     114.4MiB / 1.92GiB   5.82%     1.09kB / 0B   43.8MB / 0B   7

**Comment by hamster1963** [comment]
🤔，这边使用 debian windows 和 CentOS 环境下都未观察到内存泄露问题，有更多信息可以提供吗

**Comment by whereisxiaobaobei** [comment]
我观察到的现象就是内存占用逐渐升高直至占满内存,通过htop看到bun run server.js这个进程一直在吃内存,docker stats nezha-dash观察到就是这样的:
CONTAINER ID   NAME         CPU %     MEM USAGE / LIMIT     MEM %     NET I/O          BLOCK I/O       PIDS
<container_id>   nezha-dash   0.02%     1.491GiB / 1.92GiB    77.65%    134MB / 692MB    67.9MB / 1.8GB  8

尝试过重装系统和Docker都不行,重启docker进程或者重新拉镜像再启动内存就会降下来,但过几个小时后内存又开始占满了,我应该还要提供哪些信息呢?

**Comment by hamster1963** [comment]
下个版本将切换到 node 运行时，看看是否可以解决此问题。

**Comment by whereisxiaobaobei** [comment]
好的多谢,新版本出来之后我也关注一下

**Comment by hamster1963** [comment]
换用 node 后，观察到内存占用有所改善，可更新测试一下。

**Comment by hamster1963** [comment]
此问题应已修复。
