### ISSUE TITLE
移动端显示异常

### ISSUE THREAD

**Issue by Chilledwatermelon** [hamster1963/nezha-dash#125]
rt，
![photo_2024-11-23_17-28-36](https://github.com/user-attachments/assets/64bede42-0928-464f-bd51-8742704c51e3)
![photo_2024-11-23_17-28-46](https://github.com/user-attachments/assets/4f0fc428-e744-4c08-a02b-817a66714614)

**Comment by hamster1963** [comment]
可以尝试不同移动设备打开，观察是否仍存在此现象

**Comment by Chilledwatermelon** [comment]
安卓手机打开没问题，iPhone打开会这样

**Comment by Chilledwatermelon** [comment]
ipad也显示正常

**Comment by hamster1963** [comment]
是不是装了什么插件？ 或者代理有问题？目前无法复现此问题

**Comment by Chilledwatermelon** [comment]
我瞅瞅

**Comment by Chilledwatermelon** [comment]
我插件和代理都关了越狱都取消了hh，还是不行，不知道是不是我个人问题害

**Comment by hamster1963** [comment]
😂这个情况实在难排查，这边就先关闭 issue，后续有疑问可继续在此 issue 交流.
