### ISSUE TITLE
反馈一个关于时延图表显示的问题

### ISSUE THREAD

**Issue by whereisxiaobaobei** [hamster1963/nezha-dash#126]
时延显示图表最左边的刻度总是会被挡住,这个可以优化吗?
<img width="1012" alt="1" src="https://github.com/user-attachments/assets/d33796af-a144-4915-88b0-e66b20bab9b4">

**Comment by hamster1963** [comment]
这个是有意为之让 y 轴嵌入在图表内，在大多数情况下会更加美观，不过可以尝试新的布局

**Comment by hamster1963** [comment]
因为如果将 y 轴抽离出来占据一个空间，在视觉上图表就会变得不太平衡，因为明天尝试将 y 轴与图表内容的对比度增加，用以清晰阅读刻度

**Comment by whereisxiaobaobei** [comment]
好的,明白了

**Comment by hamster1963** [comment]
已在v1.5.1中优化，现在y具有独立的显示空间

**Comment by whereisxiaobaobei** [comment]
看到了,感谢大佬

**Comment by dsu-k** [comment]
> 已在v1.5.1中优化，现在y具有独立的显示空间

我画图的习惯是将单位单独放下面或上面，这样y轴标签宽度会小一点
