### ISSUE TITLE
安装到vps上显示不正常

### ISSUE THREAD

**Issue by whatmeans** [hamster1963/nezha-dash#128]
nezha-dash跟原面板都在一个vps上，然后都只进行vps本地的nginx反代。
原nezha面板反代访问正常。
dash安装按照教程来，compose文件和.env文件都在一个文件夹内。.env里面的配置也依照教程进行输入，内容检查过看起来没什么问题。但拉起compose后显示如图，不正常。.env里面的nezhabaseurl输入的地址经过测试，不管是反代后的，还是ip加端口，甚至是127.0.0.1加端口，都是显示环境设置不正常。这是怎么回事。
另一张图是浏览器检查里面网络的截图。访问对应api/server页面也是显示不正常。
另外，我的nginx设置是禁止ip访问vps的，会返回403，这个是不是有关系。但是baseurl里面设置的域名反代地址也是不行，就很困惑。
![dash错误](https://github.com/user-attachments/assets/29d8e274-c2a1-492d-aa67-f04b3b18c0ad)
![浏览器错误](https://github.com/user-attachments/assets/54eff423-8761-4ead-a8ec-c4db2b669e54)

**Comment by whatmeans** [comment]
忘了说了，nezha面板已经更新到最新版本

**Comment by hamster1963** [comment]
可查看 docker 容器内日志 看是否是容器访问 baseurl 不通

**Comment by whatmeans** [comment]
容器log就长这样，里面还有log的么，在哪个位置
![docker log](https://github.com/user-attachments/assets/f67aed32-0688-4870-8481-c90445d3e7d9)

**Comment by whatmeans** [comment]
![compose文件夹](https://github.com/user-attachments/assets/a0ddb113-7cd8-41b5-868e-9ebc456727d7)
![.env配置文件内容](https://github.com/user-attachments/assets/6fb75a97-6963-492c-96c4-6c55265a6cdf)

**Comment by whatmeans** [comment]
可以，vps本机可以curl到baseurl的内容
![curl内容](https://github.com/user-attachments/assets/c70f7bfc-4bb7-4a27-80ab-646d7a9b1f8f)

**Comment by whatmeans** [comment]
下面是我nignx的配置内容，网址替换过无视。 nezha面板和dash面板配置都差不多。。
我再折腾折腾。。实在不行明天再tg联系大佬。
`server {
    listen 80;
    server_name jiade.com;

    # 禁止通过 IP 直接访问
    if ($host = "") {
        return 403;
    }

    # 将 HTTP 请求重定向到 HTTPS
    location / {
        return 301 https://$host$request_uri;
    }
}

# HTTPS 配置：反代 Web 面板
server {
    listen 443 ssl;
    server_name jiade.com;

    # SSL 证书配置
    ssl_certificate /etc/letsencrypt/live/jiade.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/jiade.com/privkey.pem;

    # 推荐的 SSL 配置
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;
    ssl_prefer_server_ciphers on;

    # 禁止通过 IP 直接访问
    if ($host = "") {
        return 403;
    }

    # 反代到dash的 Web 面板
    location / {
        proxy_pass http://127.0.0.1:4123;
        proxy_http_version 1.1;

        # 保持连接
        proxy_set_header Connection "upgrade";
        proxy_set_header Upgrade $http_upgrade;

        # 传递客户端信息
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        # 超时设置
        proxy_read_timeout 300s;
        proxy_send_timeout 300s;
    }
}
`

**Comment by hamster1963** [comment]
可以试试不经过 nginx，通过容器网络连接

将 nezha-dash 与哪吒面板的容器网络连起来，可参考

![image](https://github.com/user-attachments/assets/2318a1b4-fde1-4155-8d4c-6e9874ff53cf)

**Comment by hamster1963** [comment]
nezhadash 加入到哪吒监控的容器网络后， baseurl 填写哪吒监控在容器内的 ip 地址

**Comment by Moraxyc** [comment]
## 解决方案
给docker-compose加一个环境变量HOSTNAME：
```
    environment:
      - HOSTNAME=0.0.0.0
```


## 原因分析
`server.js`里将监听地址默认设定为了主机名而不是全部地址，导致端口无法暴露出来，可能是next.js配置有问题
```
const currentPort = parseInt(process.env.PORT, 10) || 3000                                                                                         const hostname = process.env.HOSTNAME || '0.0.0.0'  
```

**Comment by hamster1963** [comment]
感谢给出的解决方案，将会加入到 docker-compose 文件中。

**Comment by whatmeans** [comment]
容器内连接终于正常了。。
```
version: "3"
services:
  nezha-dash:
    container_name: nezha-dash
    image: hamster1963/nezha-dash:latest
    volumes:
      - ./.env:/app/.env
    restart: always
    ports:
      - "4123:3000"
    networks:
      - default
      - dashboard_default

networks:
  dashboard_default:
    external: true

```
改了下compose的文件，然后改了下env的baseurl
NezhaBaseUrl=http://172.23.0.2:80
连接成功

**Comment by hamster1963** [comment]
> 容器内连接终于正常了。。
> 
> ```
> version: "3"
> services:
>   nezha-dash:
>     container_name: nezha-dash
>     image: hamster1963/nezha-dash:latest
>     volumes:
>       - ./.env:/app/.env
>     restart: always
>     ports:
>       - "4123:3000"
>     networks:
>       - default
>       - dashboard_default
> 
> networks:
>   dashboard_default:
>     external: true
> ```
> 
> 改了下compose的文件，然后改了下env的baseurl NezhaBaseUrl=http://172.23.0.2:80 连接成功

解决了就好，Docker 环境下的网络问题确实比较难排查。

**Comment by hamster1963** [comment]
如无其他问题，我就先关闭这个 issue
