### ISSUE TITLE
错误页面无法正常触发

### ISSUE THREAD

**Issue by xrgzs** [hamster1963/nezha-dash#130]
错误路径访问无法触发404错误页面

<https://nezha-cf.buycoffee.top/404> 正常

<https://nezha-cf.buycoffee.top/test> 不正常

![](https://github.com/user-attachments/assets/8e2d1afa-d560-49e5-bbfa-f9cfdd574795)

docker 部署无法访问404错误页面

<http://10.0.5.3:4123/404> 不正常

<http://10.0.5.3:4123/test> 不正常

![](https://github.com/user-attachments/assets/4d286c38-3387-4e38-a9b6-236139ece12f)

**Comment by hamster1963** [comment]
感谢提出，将会修复这个路由问题

**Comment by hamster1963** [comment]
已完成详情页路由变更与 错误/404 页面重构
