### ISSUE TITLE
总流量、UI相关建议

### ISSUE THREAD

**Issue by startle09** [hamster1963/nezha-dash#132]
1. 服务器详情里没有上下行流量显示，只有首页有全部服务器总流量
2. 首页单个服务器信息显示是否可以多增加一些项目（或可自定义显示哪些），我们可能并没有很多设备，两三个服务器还不如一行一个，每行多显示一点东西，比如比较重要的一些：国家、总流量、在线时间

感谢这么好的项目

**Comment by hamster1963** [comment]
感谢建议 计划加入单行模式 展示更多内容

**Comment by xream** [comment]
@hamster1963 请求加入 `服务` 中的 `周期性流量统计`. 感谢

**Comment by hamster1963** [comment]
感谢建议，但 v0 版本 API 中未包含周期流量数据，已在v1 官方版本中实现。

**Comment by hamster1963** [comment]
> @hamster1963 请求加入 `服务` 中的 `周期性流量统计`. 感谢

感谢建议，但 v0 版本 API 中未包含周期流量数据，已在v1 官方版本中实现。

**Comment by wanyunr** [comment]
![Clip_2024-11-30_22-20-59](https://github.com/user-attachments/assets/0aed16c9-740c-4980-9e3e-5ef5469176fa)
没有icon

**Comment by wanyunr** [comment]
> > @hamster1963 请求加入 `服务` 中的 `周期性流量统计`. 感谢
> 
> 感谢建议，但 v0 版本 API 中未包含周期流量数据，已在v1 官方版本中实现。

话说点这里应该返回主界面，不然每次回去都要手动删路径
![Clip_2024-11-30_22-28-46](https://github.com/user-attachments/assets/d7d499d3-a3a3-4147-9740-8dd25ec22743)

**Comment by hamster1963** [comment]
> > > @hamster1963 请求加入 `服务` 中的 `周期性流量统计`. 感谢
> > 
> > 
> > 感谢建议，但 v0 版本 API 中未包含周期流量数据，已在v1 官方版本中实现。
> 
> 话说点这里应该返回主界面，不然每次回去都要手动删路径 ![Clip_2024-11-30_22-28-46](https://private-user-images.githubusercontent.com/105478325/391242871-d7d499d3-a3a3-4147-9740-8dd25ec22743.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI5NzcyNzUsIm5iZiI6MTczMjk3Njk3NSwicGF0aCI6Ii8xMDU0NzgzMjUvMzkxMjQyODcxLWQ3ZDQ5OWQzLWEzYTMtNDE0Ny05NzQwLThkZDI1ZWMyMjc0My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEzMFQxNDI5MzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01ZjBiMWYxZGM4ZDQzNDAwNmI2MDZkN2ZhMGQ3MTZhNDRkMDYzYjY0NmM0YjQ3ZmIyZWE1ZTA0YTRjNjIwOWE1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.SDQiNVHFplZvJGx0oanbbFvAvtG1qoDANgsgag8i5s8)

已提交至管理后台开发者

**Comment by hamster1963** [comment]
v1.5.7 版本已添加流量信息，将关闭此 issue

**Comment by startle09** [comment]
部署试了下很好，有点瑕疵，多行情况下没对齐

![111](https://github.com/user-attachments/assets/9cbeb0a0-31bb-4e9b-9681-524e859ea415)

**Comment by hamster1963** [comment]
> 部署试了下很好，有点瑕疵，多行情况下没对齐
> 
> 
> 
> ![111](https://github.com/user-attachments/assets/9cbeb0a0-31bb-4e9b-9681-524e859ea415)

下周修复 累麻了

**Comment by hamster1963** [comment]
> 部署试了下很好，有点瑕疵，多行情况下没对齐
> 
> ![111](https://private-user-images.githubusercontent.com/189344542/391317888-9cbeb0a0-31bb-4e9b-9681-524e859ea415.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMwNTA3MDEsIm5iZiI6MTczMzA1MDQwMSwicGF0aCI6Ii8xODkzNDQ1NDIvMzkxMzE3ODg4LTljYmViMGEwLTMxYmItNGU5Yi05NjgxLTUyNGU4NTllYTQxNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwMVQxMDUzMjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZGY2NmZjYWZkYmFjMTk2YzhjOGQ4YmZlNTY5M2EyM2JhZTcwMzRmNDRlOWY3ZGRhYTQzNjdlYzY5ZDRiZjU0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.JWMx8jADe-XgFIAXvEWNhq-I1tK493bidPT7Xp2oFv4)

<img width="1130" alt="CleanShot 2024-12-01 at 16 57 26@2x" src="https://github.com/user-attachments/assets/e965b942-ccb9-455d-8c78-1ba996dabab9">

已优化
