### ISSUE TITLE
走 API 添加的机器页面上看不到

### ISSUE THREAD

**Issue by pkgogo** [hamster1963/nezha-dash#133]
通过 API 添加，在机器上装完 agent，nezha 自己的 dashboard 能正常显示，nezha-dash 里看不到

**Comment by pkgogo** [comment]
dashboard 是 `0.20.13`, nezha-dash 是最新 tag `v1.5.6`，看了下确实开启了游客隐藏，因为 dashboard 里不登录也能看就没注意. 这种情况下接口是拿不到么？

**Comment by hamster1963** [comment]
nezha-dash 会根据是否对游客隐藏这个参数筛选掉服务器，但有一个强制显示全部的环境变量，可以查看文档。
