### ISSUE TITLE
nezha-dash可获取服务器信息，但全部显示离线

### ISSUE THREAD

**Issue by beiqi7** [hamster1963/nezha-dash#135]
版本：v1.5.6-fix cloudflare分支
可获取服务器信息，总流量、服务器分类、国家信息都正常获取
环境变量尝试了两种方法，域名+端口和域名都无法让服务器在nezha-dash在线
![image](https://github.com/user-attachments/assets/33aa9a66-711d-4b6d-b156-78143c71f9b0)
![image](https://github.com/user-attachments/assets/22b7565f-4bf3-4b6a-a147-6c9efa31dbb7)

**Comment by hamster1963** [comment]
现在的在线离线判断时间是根据最后活跃时间来判断的 超过5分钟则为离线 机器上报间隔时间为多少？

**Comment by hamster1963** [comment]
请检查服务器时间
