### ISSUE TITLE
[FEAT]能不能像V0一样加上重新对接的按钮

### ISSUE THREAD

**Issue by husangou** [hamster1963/nezha-dash#140]
**面板版本（二选一）**
 V1

**需要什么？**
重新对接按钮
**额外信息**
能不能像V0一样加上重新对接的按钮，不然每次换机器都要重新重命名而且换机器的话触发任务就没法用了

**Comment by hamster1963** [comment]
这个仓库主要讨论前台的事宜，用户后台请移步https://github.com/nezhahq/admin-frontend。

**Comment by husangou** [comment]
> 这个仓库主要讨论前台的事宜，用户后台请移步[https://github.com/nezhahq/admin-frontend。](https://github.com/nezhahq/admin-frontend%E3%80%82)

404了 仓库

**Comment by hamster1963** [comment]
https://github.com/nezhahq/admin-frontend
