### ISSUE TITLE
[FEAT] 显示服务器负载

### ISSUE THREAD

**Issue by Auction99** [hamster1963/nezha-dash#145]
**面板版本（二选一）**
V0 |

**需要什么？**
显示服务器的负载

**额外信息**

**Comment by hamster1963** [comment]
请提供更多信息，在详情页面显示吗？

**Comment by Auction99** [comment]
> 请提供更多信息，在详情页面显示吗？

嗯，谢谢大佬精美的面板，非常喜欢

**Comment by hamster1963** [comment]
了解，近期计划会将全部信息显示在详情页

**Comment by hamster1963** [comment]
<img width="1105" alt="CleanShot 2024-12-01 at 16 21 09@2x" src="https://github.com/user-attachments/assets/eeca3df4-2cc6-458d-9cc7-ac9af3e782cf">

已实现
