### ISSUE TITLE
[BUG]z 服务显示异常问题

### ISSUE THREAD

**Issue by wanyunr** [hamster1963/nezha-dash#146]
**面板版本（二选一）**
V1

**描述 bug**
1. 从服务器详情返回到主界面，每次都会提示`WebSocket 连接成功`，提示过于频繁了
![Clip_2024-12-01_15-33-56](https://github.com/user-attachments/assets/d5d47af9-b127-4687-b9f9-f2b382cc1590)
**返回就会提示**
![Clip_2024-12-01_15-32-52](https://github.com/user-attachments/assets/1e54642b-d97c-4075-a7e3-d78c3d6d77c6)

2. 这个服务在后端选择并没有在服务显示，但是还是会有
![Clip_2024-12-01_15-35-39](https://github.com/user-attachments/assets/47f3be13-401e-46c7-9f46-f43167f4c63e)
![image](https://github.com/user-attachments/assets/16f1bedd-87fd-4748-96a9-e9d4e7c23668)

**屏幕截图**
有屏幕截图可以帮助更快定位到问题

**额外信息**
可附上其他需要的额外信息

**Comment by hamster1963** [comment]
1. 已优化弹出提示
2. 等待后端修复
