### ISSUE TITLE
[BUG]详情页[负载]小数点后位数太多

### ISSUE THREAD

**Issue by xCss** [hamster1963/nezha-dash#147]
**面板版本（二选一）**
V0

**描述 bug**
详情页`负载`小数点后位数太多

**屏幕截图**
<img width="1103" alt="image" src="https://github.com/user-attachments/assets/9d2501a2-0251-445b-8b48-4218785b9305">

**额外信息**
v1.6.2

**Comment by hamster1963** [comment]
今晚修

**Comment by hamster1963** [comment]
今晚修

**Comment by hamster1963** [comment]
累倒下了，明早修

**Comment by hamster1963** [comment]
修了
