### ISSUE TITLE
[BUG]字体显示糊

### ISSUE THREAD

**Issue by wanyunr** [hamster1963/nezha-dash#148]
**面板版本（二选一）**
V1

**描述 bug**
如图，默认主题的文字显示很奇怪，数字会缺角，很糊
平台：Windows 10，Edge浏览器，1080P显示屏，
手机上没复现，可能是默认字体适配问题？其他地方也未出现如此明显的问题
**屏幕截图**
![Clip_2024-12-02_00-14-01](https://github.com/user-attachments/assets/f6fb2361-2597-4a00-8359-cda2a497c4f5)

**额外信息**
可附上其他需要的额外信息

**Comment by hamster1963** [comment]
未查看到图片，是否可以重新上传？

**Comment by wanyunr** [comment]
> 未查看到图片，是否可以重新上传？

![Clip_2024-12-02_00-14-01](https://github.com/user-attachments/assets/25a5cb49-ab2b-45cc-8101-2d6b9a9a7a6d)

**Comment by hamster1963** [comment]
暂时无法复现，明早回公司试试

**Comment by hamster1963** [comment]
<img width="981" alt="CleanShot 2024-12-02 at 02 31 14@2x" src="https://github.com/user-attachments/assets/5dbf5c57-9dda-4909-b12c-9cd25ecd6aba">

暂时无法复现，是否可以检查本地字体设置？
