### ISSUE TITLE
大佬没有考虑过构建一个docker镜像上传到dockerhub吗

### ISSUE THREAD

**Issue by miaowmint** [hamster1963/nezha-dash#15]
境内鸡每次build都非常非常慢，所以希望大佬能打包成docker镜像并上传到dockerhub

如果觉得每次更新都要打包一个镜像很麻烦，也可以用github action自动打包并上传

**Comment by hamster1963** [comment]
当前项目中的环境变量存储在.env 文件中，next.js 在构建时就将变量嵌入到服务端的代码中，构建后环境变量无法修改，无法构建一个统一的 docker 镜像。
目前仓库内提供了 Dockerfile，可以手动配置GitHub Action 去自行构建镜像至 github 镜像仓库或者阿里云的镜像仓库中。
[workflows 文件](https://gist.github.com/hamster1963/7aaebd391722e3bf8c92b0538de02fc7)

**Comment by miaowmint** [comment]
好吧 我看看

**Comment by hamster1963** [comment]
正在基于next-runtime-env构建新的Docker镜像

**Comment by hamster1963** [comment]
#18 已支持 Docker部署，部署教程编写后将会合并入主分支。

**Comment by hamster1963** [comment]
Docker部署方式已实现。
[Docker 部署](https://buycoffee.top/blog/tech/nezha-docker)
