### ISSUE TITLE
[SUGGEST]可否更换一下当前时间的位置

### ISSUE THREAD

**Issue by w243420707** [hamster1963/nezha-dash#151]
**面板版本（二选一）**
V1

**需要改进的？**

-
![image](https://github.com/user-attachments/assets/d55caeb5-1068-4d22-a6c6-f13411cad79d)
支持大佬！大佬辛苦！

**Comment by hamster1963** [comment]
这个是考虑到移动端与美观度做出的考量 暂时不会改变。

**Comment by w243420707** [comment]
> 这个是考虑到移动端与美观度做出的考量 暂时不会改变。

好滴 谢谢佬回复
