### ISSUE TITLE
[V1 | SUGGEST]网络图表可以多选

### ISSUE THREAD

**Issue by lingbaoboy** [hamster1963/nezha-dash#155]
**面板版本（二选一）**
V1

**需要改进的？**
目前网络图表第一次进入是会将所有监控全部绘图，然后点击一个监控会对一个监控进行绘图，有时候需要手动多选，比如选择两个监控进行绘图以比较网络，所以希望增加手动多选。

绘制图标可以选择更长的时间，目前最长仅能显示24h，经常需要查看周或月的网络波动

-

**Comment by hamster1963** [comment]
官方只记录 24 小时数据，因此没有更多数据可供查看

**Comment by lingbaoboy** [comment]
那手动多选还是支持一下，记录数据长短就看官方后边会不会改了

**Comment by hamster1963** [comment]
https://github.com/hamster1963/nezha-dash-react/releases/tag/v0.6.4

等待官方发版
