### ISSUE TITLE
[BUG]qq浏览器一直显示 WebSocket 连接中

### ISSUE THREAD

**Issue by 2689508458** [hamster1963/nezha-dash#156]
**面板版本（二选一）**
V0 | V1
V1
**描述 bug**
在这里描述 bug 的相关信息
qq浏览器一直显示 WebSocket 连接中 获取不到 其他浏览器正常
**屏幕截图**
有屏幕截图可以帮助更快定位到问题
![image](https://github.com/user-attachments/assets/e1908876-735c-4e35-a165-a0fe4c703495)

**额外信息**
可附上其他需要的额外信息

**Comment by hamster1963** [comment]
已在新版中修复此问题，请等待官方新版发布，谢谢🙏

**Comment by iTofu** [comment]
```
©2020-2024 Nezha 1.0.22
主题-[nezha-dash](https://github.com/hamster1963/nezha-dash)(fbf02a1)
```
请问 nezha 这个版本还没有包含此次修复吗？macOS 在 Safari 上持续出现该问题，Chrome 正常。

**Comment by hamster1963** [comment]
> ```
> ©2020-2024 Nezha 1.0.22
> 主题-[nezha-dash](https://github.com/hamster1963/nezha-dash)(fbf02a1)
> ```
> 
> 请问 nezha 这个版本还没有包含此次修复吗？macOS 在 Safari 上持续出现该问题，Chrome 正常。

已修复这个问题，请问safari 是什么呢，我在 macos12 13 14 15 都测试过没有问题，是否与 surge 代理有关？

**Comment by iTofu** [comment]
> > ```
> > ©2020-2024 Nezha 1.0.22
> > 主题-[nezha-dash](https://github.com/hamster1963/nezha-dash)(fbf02a1)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 请问 nezha 这个版本还没有包含此次修复吗？macOS 在 Safari 上持续出现该问题，Chrome 正常。
> 
> 已修复这个问题，请问safari 版本是什么呢，我在 macos12 13 14 15 都测试过没有问题，是否与 surge 代理有关？

macOS 15.1.1 (24B91)

似乎确实与 Surge 有关，关闭退出 Surge 后 Safari 也正常了。
