### ISSUE TITLE
[BUG] VPS 网络监控详情页 UI 优化

### ISSUE THREAD

**Issue by flyflas** [hamster1963/nezha-dash#157]
**面板版本（二选一）**
V1

**描述 bug**
如图，当监控节点数量较少时，并未填满宽度
![CleanShot 2024-12-02 at 19 48 12@2x](https://github.com/user-attachments/assets/24f9a4f7-4db6-4605-95ec-8a1d4dd25bf9)

**Comment by hamster1963** [comment]
感谢提出，这块优化起来较为困难，明早回看看

**Comment by hamster1963** [comment]
在 nezha-dash 与 v1 中均已修复
