### ISSUE TITLE
弹500错误叫检测环境变量

### ISSUE THREAD

**Issue by q42602736** [hamster1963/nezha-dash#158]
**面板版本（二选一）**
V0 

一会能用，一会就弹500错误

![1733200898827](https://github.com/user-attachments/assets/0a73880d-7536-491d-89ea-14cb67a3084e)

vercel我看log里面有错误
![1733200937570](https://github.com/user-attachments/assets/de804c81-1a83-41ba-8045-1b5b4dd161b1)

**Comment by q42602736** [comment]
![1733201250060](https://github.com/user-attachments/assets/556d8706-4a2a-4daa-b85f-5e460f0036bf)

**Comment by hamster1963** [comment]
这个是因为 vercel 连接到你设置的 baseurl 有问题 可能超时了 你可以尝试修改设置里 function 的地域 靠近你的面板

**Comment by q42602736** [comment]
> 这个是因为 vercel 连接到你设置的 baseurl 有问题 可能超时了 你可以尝试修改设置里 function 的地域 靠近你的面板
我是用的Argo 隧道的那个哪吒，跟这个有关系吗
