### ISSUE TITLE
许可证问题

### ISSUE THREAD

**Issue by Moraxyc** [hamster1963/nezha-dash#159]
致维护者：

您好！

为了确保在分发nezha软件包时不发生歧义，请为专用于nezha的前端版本`hamster1963/nezha-dash-react`及`nezhahq/user-frontend-backup`添加LICENSE，明确开源许可范围。

**Comment by hamster1963** [comment]
好的，现在加上，感谢提醒。

**Comment by hamster1963** [comment]
已添加 MIT 许可证，nezhahq/user-frontend-backup 会在下次发版时进行同步
