### ISSUE TITLE
[BUG]反馈个这逼死强迫症的bug

### ISSUE THREAD

**Issue by Hansen1018** [hamster1963/nezha-dash#160]
**面板版本（二选一）**
V0

**描述 bug**
在这里描述 bug 的相关信息

**屏幕截图**
![2024-12-03 165432](https://github.com/user-attachments/assets/73bf53ed-0b20-4451-bc2e-1c1b5d5760f8)

**额外信息**
ping 延迟数据CSS样式溢出

**Comment by hamster1963** [comment]
了解，今晚修复

**Comment by hamster1963** [comment]
修了
