### ISSUE TITLE
[BUG] 麻烦问下最新的 nezha api token 在哪？

### ISSUE THREAD

**Issue by iTofu** [hamster1963/nezha-dash#161]
**面板版本（二选一）**
V0

**描述 bug**
根据 https://nezha.wiki/guide/dashboard.html + https://buycoffee.top/blog/tech/nezha-docker 配置的，找不到文档中所示的 API Token 选项。后台截图如下。

**屏幕截图**
<img width="204" alt="Xnip2024-12-04_02-32-37" src="https://github.com/user-attachments/assets/1c90a40a-0c6b-4bb8-a2e3-9e22447d1d83">

**额外信息**
可附上其他需要的额外信息

**Comment by hamster1963** [comment]
您安装的是 v1 的新版 ，已内置了此仪表盘。

**Comment by hamster1963** [comment]
V1 版本目前为前后端分离架构，未加入 API Token ，可通过手动用户鉴权的方式获取。

**Comment by bluefish-08** [comment]
> V1 版本目前为前后端分离架构，未加入 API Token ，可通过手动用户鉴权的方式获取。

请问要如何获取呢

**Comment by hamster1963** [comment]
V1的文档为什么不再有API文档？
同样是得益于前后端分离，V1版本后端的API已经没有特别提及的必要了，内置的 Swagger 已经有非常详尽的文档，Dashboard 开启 Debug 模式后可以访问路径 /swagger/index.html 查看详情

**Comment by bluefish-08** [comment]
新版nezha貌似没有返回主页的那个按钮 有点不方便 后续会修改更新吗

**Comment by hamster1963** [comment]
> 新版nezha貌似没有返回主页的那个按钮 有点不方便 后续会修改更新吗

我目前只负责用户前台这块，后台返回按钮看到有很多人提出，但是否加入还是得看后台页面开发者的决定
