### ISSUE TITLE
[SUGGEST]建议把页面显示未知项自动隐藏

### ISSUE THREAD

**Issue by Hansen1018** [hamster1963/nezha-dash#165]
**面板版本（二选一）**
V0 | V1

**需要改进的？**

有很多设备无法正确识别系统和GPU，建议考虑为未知字样后自动隐藏此项

![2024-12-04 141936](https://github.com/user-attachments/assets/4ccb8046-daa4-4317-bcc9-5bac471396b9)

**Comment by hamster1963** [comment]
V0 | V1 版本已优化完成

**Comment by Hansen1018** [comment]
也是今晚版本落地嘛？

**Comment by hamster1963** [comment]
大概率是

**Comment by Hansen1018** [comment]
世界地图还会有嘛？

**Comment by hamster1963** [comment]
也会在今晚的版本中包含
