### ISSUE TITLE
[BUG] 面板个别地方翻译未完成 望优化

### ISSUE THREAD

**Issue by Theo-Messi** [hamster1963/nezha-dash#166]
**面板版本（二选一）**
V1

**描述 bug**
个别地方翻译未完成

**屏幕截图**
<img width="568" alt="image" src="https://github.com/user-attachments/assets/a987e681-81a6-4838-b6a7-7378ade6b41c">

<img width="359" alt="image" src="https://github.com/user-attachments/assets/9f973510-abea-4e3b-8f45-690a97f0e05e">

运行时间的单位为Days 但是过期时间却是天

**Comment by hamster1963** [comment]
好的 您也可以通过 pr 的方式帮忙翻译下，个人精力有限☺️

**Comment by hamster1963** [comment]
已优化
