### ISSUE TITLE
[BUG]主页海外TCPING值无法正常显示及更新

### ISSUE THREAD

**Issue by Hansen1018** [hamster1963/nezha-dash#167]
**面板版本（二选一）**
V1

**描述 bug**
主页海外TCPING值无法正常显示及更新，在服务器ping页面正常显示数据

**屏幕截图**
![屏幕截图 2024-12-05 184147](https://github.com/user-attachments/assets/19508579-d387-4a95-a347-188f45dc718a)

**额外信息**
可附上其他需要的额外信息

**Comment by hamster1963** [comment]
这个问题请至 nezha 仓库发起，感谢🙏

**Comment by Hansen1018** [comment]
好的，以为是UI问题
