### ISSUE TITLE
[BUG]V1 服务器列表名称及logo错位

### ISSUE THREAD

**Issue by Hansen1018** [hamster1963/nezha-dash#168]
**面板版本（二选一）**
V1

**描述 bug**
又是个逼死强迫症的bug 哈

**屏幕截图**
![2024-12-05 230050](https://github.com/user-attachments/assets/2a91fa58-a859-4152-a2a2-0baedd9b5d4e)

**额外信息**
可附上其他需要的额外信息

**Comment by hamster1963** [comment]
不对呀🤔 这是由于没获取到地区不显示旗帜就留空了 不是还是对齐的吗😂

**Comment by Hansen1018** [comment]
> 不对呀🤔 这是由于没获取到地区不显示旗帜就留空了 不是还是对齐的吗😂

之前也是没有旗帜比现在顺眼，最新版咋怪怪的

**Comment by hamster1963** [comment]
没有动过这部分的代码呀😂是否可以给出更多信息？或者说希望改成什么样？

**Comment by Hansen1018** [comment]
> 没有动过这部分的代码呀😂是否可以给出更多信息？或者说希望改成什么样？

恢复到1.0.21版就好

**Comment by hamster1963** [comment]
> > 没有动过这部分的代码呀😂是否可以给出更多信息？或者说希望改成什么样？
> 
> 
> 
> 恢复到1.0.21版就好

问题是没改过呀😳 这怎么改

**Comment by Hansen1018** [comment]
> > > 没有动过这部分的代码呀😂是否可以给出更多信息？或者说希望改成什么样？
> > 
> > 
> > 恢复到1.0.21版就好
> 
> 问题是没改过呀😳 这怎么改

https://github.com/hamster1963/nezha-dash/issues/167 参考 总觉得这版顺眼

**Comment by hamster1963** [comment]
明天改成拿不到地区代码就不显示旗帜那块好了

**Comment by hamster1963** [comment]
> > > > 没有动过这部分的代码呀😂是否可以给出更多信息？或者说希望改成什么样？
> 
> > > 
> 
> > > 
> 
> > > 恢复到1.0.21版就好
> 
> > 
> 
> > 问题是没改过呀😳 这怎么改
> 
> 
> 
> https://github.com/hamster1963/nezha-dash/issues/167 参考 总觉得这版顺眼
> 
> 
> 
> 我更改了排序的锅？

我怎么感觉和现在没啥区别呢╮(•́ω•̀)╭

**Comment by Hansen1018** [comment]
把长名称和短名称混杂显示优化下，另外为了安全不显示系统版本号的话 把-删除吧

**Comment by hamster1963** [comment]
> 把长名称和短名称混杂显示优化下，另外为了安全不显示系统版本号的话 把-删除吧

系统版本这个明早可以修 名称排版你可以 pr 一下吗，个人精力有限

**Comment by Hansen1018** [comment]
> > 把长名称和短名称混杂显示优化下，另外为了安全不显示系统版本号的话 把-删除吧
> 
> 系统版本这个明早可以修 名称排版你可以 pr 一下吗，个人精力有限

好的

**Comment by Hansen1018** [comment]
移动端UI错位更严重

![Screenshot_2024-12-06-06-19-56-452_com android browser](https://github.com/user-attachments/assets/2997775a-9d49-4e46-9805-6bc375563a54)

**Comment by hamster1963** [comment]
已修复
