### ISSUE TITLE
[FEAT]

### ISSUE THREAD

**Issue by vbskycn** [hamster1963/nezha-dash#169]
**面板版本（二选一）**
 V1

**需要什么？**

概览可以否按分组统计显示

默认是all
这时显示所有的服务器概览

选中不同的分组后
概览 变成这个分组所有的服务器的概览，应该会更好。

就是不知道实现会不会很难，但是很实用，因为有些是挂了内网服务器的监控，比如pve，上传下载量都是很大的，
如果是挂了pve之类的小鸡，这样的话概览就少了应有的效果

![image](https://github.com/user-attachments/assets/899d3fb2-0b11-4418-b1aa-09be1ad6ffd1)

**额外信息**

**Comment by hamster1963** [comment]
https://github.com/user-attachments/assets/e3b2d663-d105-4077-9c45-021febcd5ae7

已实现
