### ISSUE TITLE
[BUG]哪吒v1面板内的nezhadash无法点击顶部按钮

### ISSUE THREAD

**Issue by wopupa21** [hamster1963/nezha-dash#172]
**面板版本（二选一）**
 V1

**描述 bug**
顶部四个（服务器总数、在线服务器、离线服务器、网络）点击后无反应，与之前的v0+dash的点击后自动罗列排名不同吗

**屏幕截图**
![image](https://github.com/user-attachments/assets/71d895a9-eb72-479d-814c-099629428543)

**额外信息**
可附上其他需要的额外信息

**Comment by hamster1963** [comment]
已实现，今晚或明天的版本就会加入
