### ISSUE TITLE
[BUG]晚上0点之后时间显示的是12:xx AM ,应该是0:xx AM

### ISSUE THREAD

**Issue by Fokkyp** [hamster1963/nezha-dash#174]
**面板版本（二选一）**
V1

**描述 bug**
晚上0点之后时间显示的是12:xx AM ,应该是0:xx AM吧

**屏幕截图**
![image](https://github.com/user-attachments/assets/e4da6e08-e041-4a0e-bef9-777d0ef26a9c)

**额外信息**
无

**Comment by hamster1963** [comment]
如果用 0:00 AM 可能会让人困惑，因为在12小时制中没有"0点"的概念
