### ISSUE TITLE
[SUGGEST][V1]图表相关疑问

### ISSUE THREAD

**Issue by dsu-k** [hamster1963/nezha-dash#175]
**面板版本**
V1
![image](https://github.com/user-attachments/assets/270d5279-2f27-4f40-8f6a-80d17a692bed)
有一个疑问
既然不记录历史数据，那这些占用了大量空间的图表模块有什么意义呢？
我想没人会一直开着这个界面让他实时记录吧,而且一刷新就数据没了
（想看历史数据的可以用别的程序）
![image](https://github.com/user-attachments/assets/f8017069-4ee5-4248-8f17-539ca9201ed4)

**Comment by hamster1963** [comment]
预留功能
