### ISSUE TITLE
[FEAT] 服务器温度折叠显示

### ISSUE THREAD

**Issue by uubulb** [hamster1963/nezha-dash#176]
**面板版本（二选一）**
V1

**需要什么？**
希望服务器详情页面默认可以折叠显示温度，和之前的官方 v0 主题 Server Status 一样。
优先度不是很高，毕竟现在显示空间比较充裕

**额外信息**
Server Status 维护了一个传感器名称列表用于筛选显示 CPU 核心温度，可以参考一下。

https://github.com/nezhahq/nezha/blob/9c25540e15bc8d77c0a21d23c0c64eaaa8941f8c/resource/template/theme-server-status/home.html#L54-L70

**Comment by hamster1963** [comment]
好的，近期改进为折叠展示，优先显示CPU 核心温度
