### ISSUE TITLE
[BUG] 移动端页脚错误

### ISSUE THREAD

**Issue by yorunning** [hamster1963/nezha-dash#182]
**面板版本（二选一）**
V1

**描述 bug**
在移动端页头由`登录`变为`管理后台`后，页脚的内容对其出错。

**屏幕截图**
<img width="378" alt="截屏2024-12-12 18 52 08" src="https://github.com/user-attachments/assets/ef5a45df-a0c2-496e-9c4a-78e3f4f834c7" />
<img width="378" alt="截屏2024-12-12 18 52 46" src="https://github.com/user-attachments/assets/12f4f027-4e52-4a30-8a58-79282e690b53" />

**额外信息**
/

**Comment by hamster1963** [comment]
今晚修

**Comment by hamster1963** [comment]
已提交修复代码
