### ISSUE TITLE
[BUG] 标题位置缺失图标文件 apple-touch-icon.png

### ISSUE THREAD

**Issue by DearTanker** [hamster1963/nezha-dash#184]
**面板版本（二选一）**
V1

**描述 bug**
标题位置缺失图标文件
apple-touch-icon.png 404

**屏幕截图**
![image](https://github.com/user-attachments/assets/79448330-0c74-48e8-93ea-c3bfd3db8e09)

**额外信息**
可附上其他需要的额外信息

**Comment by hamster1963** [comment]
<img width="778" alt="CleanShot 2024-12-13 at 15 03 26@2x" src="https://github.com/user-attachments/assets/df0b6518-4631-446e-b4f2-8be8c863ab21" />

无法复现

**Comment by DearTanker** [comment]
额，那我再检查一下，可能是 nginx 配置出问题了，我按照官方文档再查查。

**Comment by hamster1963** [comment]
感谢回复，现在是前后端分离的，因此这个操作应该不会造成其他的问题
