### ISSUE TITLE
[BUG] 无法添加通知

### ISSUE THREAD

**Issue by LQ2002** [hamster1963/nezha-dash#187]
**面板版本（二选一）**
V1

**描述 bug**
添加通知填写完相关信息后，点击确认无法完成添加，一直没有响应，有时又能添加（还可能重复）

**屏幕截图**
<img width="1366" alt="image" src="https://github.com/user-attachments/assets/bfd77b6e-d6f0-4cdc-9024-6d961aec7a85" />

**额外信息**
可附上其他需要的额外信息

**Comment by hamster1963** [comment]
请至后台仓库发起 issue
