### ISSUE TITLE
[BUG] 切换语言按钮有点问题

### ISSUE THREAD

**Issue by naiba** [hamster1963/nezha-dash#188]
**面板版本（二选一）**
V1

**描述 bug**
在这里描述 bug 的相关信息

**屏幕截图**
<img width="470" alt="Screenshot 2024-12-14 at 14 38 35" src="https://github.com/user-attachments/assets/d354ff4b-f7a4-4933-abed-e50656b74ebb" />

**额外信息**
qio.ng

**Comment by hamster1963** [comment]
已修复
