### ISSUE TITLE
[FEAT] 自定义代码隐藏双排累计上传下载数据

### ISSUE THREAD

**Issue by naiba** [hamster1963/nezha-dash#189]
**面板版本（二选一）**
V1

![image](https://github.com/user-attachments/assets/48933813-2e58-46ff-b68d-cb77f351ccc9)

**Comment by hamster1963** [comment]
自定义代码：
<script>
    window.ShowNetTransfer = "false";
</script>

<img width="421" alt="CleanShot 2024-12-15 at 02 08 15@2x" src="https://github.com/user-attachments/assets/c2876e76-87d6-469a-a306-8d07a7bd37db" />

<img width="572" alt="CleanShot 2024-12-15 at 02 09 06@2x" src="https://github.com/user-attachments/assets/4fbd0b40-b2e2-4fb6-9be8-6de676f46f2f" />
