### ISSUE TITLE
[FEAT] 前台 和 后台的 header 右边有点空 大佬配个插画

### ISSUE THREAD

**Issue by naiba** [hamster1963/nezha-dash#191]
**面板版本（二选一）**
V1

- [x] 前台
![image](https://github.com/user-attachments/assets/7073e002-edba-4ac9-a3a1-a108e5ca8de5)

- [x] 后台

<img width="1214" alt="Screenshot 2024-12-14 at 16 54 20" src="https://github.com/user-attachments/assets/cd40336d-4324-4fa2-a6bd-7e9a969fdbf9" />

**Comment by hamster1963** [comment]
已完成
