### ISSUE TITLE
[SUGGEST]保留package-lock.json

### ISSUE THREAD

**Issue by Moraxyc** [hamster1963/nezha-dash#193]
**面板版本（二选一）**
Both

**需要改进的？**

Bun目前的可复现性构建似乎存在一些问题，在同样情况下的表现不一致。同时，bun暂时还不支持offline tarball缓存，无法做到构建产物完全可控。完全抛弃`package-lock.json`切换到`bun.lockb`稍显激进，建议仍然保留`package-lock.json`以支持nodejs npm构建

https://github.com/oven-sh/bun/issues/7956

**Comment by hamster1963** [comment]
package-lock.json 为其他 pr 的文件项，没有对其进行维护，因此移除
