### ISSUE TITLE
[FEAT]面板自定义代码支持替换Logo和favicon

### ISSUE THREAD

**Issue by yahuisme** [hamster1963/nezha-dash#195]
**面板版本（二选一）**
V1

**需要什么？**
面板自定义代码支持替换Logo和favicon，类似于自定义背景图片的这种：
  window.CustomLogo = "image.png";
  window.CustomFavicon = "image.png";

**额外信息**
无

**Comment by hamster1963** [comment]
<script>
    window.ShowNetTransfer = "false";
    window.DisableAnimatedMan = "true";
    window.CustomLogo="https://buycoffee.top/_next/static/media/avatar.26685e5d.webp";
    window.CustomDesc = "dev"
</script>


<img width="551" alt="CleanShot 2024-12-16 at 21 22 40@2x" src="https://github.com/user-attachments/assets/bf5d44fc-60be-4a11-91f9-d89d0d0b33f9" />
