### ISSUE TITLE
[SUGGEST]前台卡片紫色配色建议换成蓝色

### ISSUE THREAD

**Issue by yahuisme** [hamster1963/nezha-dash#201]
**面板版本（二选一）**
V1

**需要改进的？**
前台网络下行流量的字体紫色建议换成绿色
前台卡片网络带宽的紫色建议换成蓝色
这样页面的颜色就是红绿蓝三色，视觉上显得更和谐。
-
![IMG_4302](https://github.com/user-attachments/assets/633430fc-de97-4f36-a82f-d9f5211d8f6b)

**Comment by hamster1963** [comment]
已优化
