### ISSUE TITLE
[BUG]自定义背景图片在手机上没有自适应屏幕高度

### ISSUE THREAD

**Issue by yahuisme** [hamster1963/nezha-dash#202]
**面板版本（二选一）**
V1

**描述 bug**
自定义背景图片在电脑上已经优化，但在手机上仍然没有固定显示和自适应屏幕尺寸，导致卡片过多的时候，拉伸显示模糊

**屏幕截图**

**额外信息**
测试设备：iOS16 iphone8P

**Comment by hamster1963** [comment]
已优化
