### ISSUE TITLE
[BUG]公开备注里面自动续期失效

### ISSUE THREAD

**Issue by MoeBai** [hamster1963/nezha-dash#204]
**面板版本（二选一）**
V1

**描述 bug**
公开备注里面自动续期失效

**屏幕截图**
![image](https://github.com/user-attachments/assets/64e3afcb-addc-4111-97ca-08b5d2f4cf23)

**额外信息**
公开备注如下
![image](https://github.com/user-attachments/assets/804c0ab0-95b6-4fa8-8c24-23f770c7e49c)

**Comment by hamster1963** [comment]
已完成
