### ISSUE TITLE
[SUGGEST] 改用TPE旗帜表示TW地区

### ISSUE THREAD

**Issue by yumusb** [hamster1963/nezha-dash#208]
**面板版本（二选一）**
V1

**需要改进的？**

现阶段直接将TW地区采用了CN 五星红旗
```tsx
  if (supportsEmojiFlags && country_code.toLowerCase() === "tw") {
    country_code = "cn"
  }
```
毋庸置疑，这是正确的。
但两者在网络地域上代表不同的地区，直接更改可能会给用户带来混淆。建议使用 体育赛事中的 TPE旗帜 ，此旗帜是大陆地区承认的可以表示台湾地区的旗帜。且是公认的。
![](https://github.com/7kfpun/flag-css/raw/refs/heads/master/dist/flags/tpe.svg)

参考项目： 
https://github.com/7kfpun/flag-css 
https://github.com/7kfpun/flag-css/blob/master/dist/flags/tpe.svg

**Comment by hamster1963** [comment]
请问 emoji 中是否包含次旗帜？

**Comment by hamster1963** [comment]
现在是 emoji 优先，可能 emoji 下还是得采用 cn 国旗，现在 svg 下台湾旗帜可以正常显示

**Comment by hamster1963** [comment]
这个判断目前只针对 emoji 环旗帜

**Comment by yumusb** [comment]
emoji 国行的 应该都不支持那个旗帜的。可以尝试SVG的。
SVG也需要使用TPE，否则一些人在国内的域名使用，例如有备案类的 ，可能带来问题。

**Comment by hamster1963** [comment]
了解，我认为这个改动可能需要社区进行讨论一下

**Comment by moelinmtf** [comment]
> 感觉显示豆腐块也比贴个🇨🇳强 至少mac可以改语言显示

赞同的，要的是一眼看出来是哪里的，同时有国内机和台湾机的情况下不好分辨

**Comment by yahuisme** [comment]
没有台湾鸡，还真不知道台湾竟然显示CN旗？

**Comment by iilemon** [comment]
建议换手机解决。@hamster1963 close
