### ISSUE TITLE
[SUGGEST]手机版的网络带宽和流量信息等备注居中显示

### ISSUE THREAD

**Issue by yahuisme** [hamster1963/nezha-dash#210]
**面板版本（二选一）**
V1

**需要改进的？**

- 手机上网络带宽和流量信息等备注居中显示，应该比居左视觉上效果更协调。
- 借图：
![QQ图片20241220163725](https://github.com/user-attachments/assets/d5583e9e-5e52-447f-89fa-9b317515cbfd)

**Comment by hamster1963** [comment]
<img width="552" alt="CleanShot 2024-12-20 at 16 48 43@2x" src="https://github.com/user-attachments/assets/f353d431-4707-4e69-be49-f0f4b8fef915" />

已优化
