### ISSUE TITLE
[FEAT]在服务器的自定义信息中加入点击自定义跳转链接

### ISSUE THREAD

**Issue by wixxm** [hamster1963/nezha-dash#211]
**面板版本（二选一）**
V0 | V1
V1版本
**需要什么？**
在服务器的自定义信息中加入点击自定义跳转链接
**额外信息**
可以在服务器备注中添加一个自定义点击跳转链接，方便到期续费的时候一键直达。

**Comment by hamster1963** [comment]
自定义备注链接与目前点击卡片进入详情页交互一致，可能会带来交互上的困惑

**Comment by wixxm** [comment]
> 自定义备注链接与目前点击卡片进入详情页交互一致，可能会带来交互上的困惑

好像是的 会产生误触

**Comment by hamster1963** [comment]
此需求暂时搁置
