### ISSUE TITLE
[SUGGEST] 编辑服务器时的弹窗不会在切换标签页或点击弹窗以外空白区域时自动关闭

### ISSUE THREAD

**Issue by SanQianQVQ** [hamster1963/nezha-dash#213]
**面板版本（二选一）**
V1

**需要改进的？**
在修改一些东西时经常需要**来回切换标签页**或者复制粘贴的场景，比如在其他标签页查看服务器的详细信息（到期时间等）并填写备注。
但现阶段发现：
- 当切出标签页再切回时，编辑服务器的弹窗会自动关闭，并且该关闭不会保存已填写的信息
- 弹窗打开时，若误触空白区也会关闭弹窗

在填写备注的时候非常不方便，经常需要重复操作。

**Comment by SanQianQVQ** [comment]
想了一下，可能有的人习惯操作点击空白区直接关闭弹窗而不是手动点击关闭按钮。
提供一个开关此功能的开关会不会更好一些

**Comment by hamster1963** [comment]
请至 admin 仓库发起此 issue。

**Comment by SanQianQVQ** [comment]
> 请至 admin 仓库发起此 issue。

🌿 原来前端和后端是两个theme，辛苦大佬了
