### ISSUE TITLE
[SUGGEST]建议主题文件的apple-touch-icon.png可以去掉或做隐藏

### ISSUE THREAD

**Issue by yahuisme** [hamster1963/nezha-dash#215]
**面板版本（二选一）**
V1

**需要改进的？**

-后台变量替换网站logo和favicon后，主题里的apple-touch-icon.png文件仍然在苹果手机书签上默认显示，无法替换掉。

**Comment by hamster1963** [comment]
这个是 safari 的缓存策略问题，在 chrome 上是正常的
