### ISSUE TITLE
[SUGGEST]希望可以把前端点击网络自动排序的功能加回来

### ISSUE THREAD

**Issue by wixxm** [hamster1963/nezha-dash#217]
**面板版本（二选一）**
V0 | V1
V1
**需要改进的？**
之前前端可以通过点击网络直接根据速度进行排名，现在需要在新的按钮上进行选择，可以把原来那个点击网路可以自动排序的功能加回来吗？查看网络更为方便一些。
-

**Comment by hamster1963** [comment]
1.顶部按钮这个再加上这个操作逻辑可能会造成困惑
2.已优化

**Comment by wixxm** [comment]
> 1.顶部按钮这个再加上这个操作逻辑可能会造成困惑 2.已优化

大佬威武
