### ISSUE TITLE
[SUGGEST]电脑版固定顶部服务器名称时的排版

### ISSUE THREAD

**Issue by yahuisme** [hamster1963/nezha-dash#218]
**面板版本（二选一）**
V1

**需要改进的？**

-电脑版选择固定顶部服务器名称时，剩余天数和价格信息可以和手机版一样，在一行显示，这样应该更加美观简洁。
![QQ截图20241224133607](https://github.com/user-attachments/assets/d4f64f26-614a-4096-9a28-689e436ade35)

**Comment by hamster1963** [comment]
已优化
