### ISSUE TITLE
[SUGGEST]亮色主题下的地图透明度过高

### ISSUE THREAD

**Issue by yahuisme** [hamster1963/nezha-dash#219]
**面板版本（二选一）**
V1

**需要改进的？**

- 亮色主题下地图透明度过高，导致和背景图片混淆，暗色背景下无问题。
![QQ截图20241225144858](https://github.com/user-attachments/assets/1381f367-91af-4df0-8ebf-435c0e1533b4)
![QQ图片20241225144919](https://github.com/user-attachments/assets/84e68d5b-9166-4c58-bbca-09bde9313487)

**Comment by hamster1963** [comment]
<img width="1144" alt="CleanShot 2024-12-25 at 15 27 21@2x" src="https://github.com/user-attachments/assets/2bad89a7-0bb7-4af7-af1b-ddb60860c59f" />

已增加遮罩
