### ISSUE TITLE
[SUGGEST] 可用性监控和流量监控能否兼容分组

### ISSUE THREAD

**Issue by miaojior** [hamster1963/nezha-dash#220]
**面板版本（二选一）**
V1

**需要改进的？**

对于隐藏的服务器同时隐藏其流量监控

对于不同的标签页也只显示对应页面中agent的流量监控
包括服务可用性监控 只显示当前页面中agent 的服务可用性百分比

-

**Comment by hamster1963** [comment]
暂无排期，有点忙，欢迎 pr

**Comment by hamster1963** [comment]
1.已实现
2.服务可用性监控是在后端计算，无法分组
