### ISSUE TITLE
【问题求助】图标问题、默认语言、排序问题

### ISSUE THREAD

**Issue by ssln5014** [hamster1963/nezha-dash#29]
- 在某些字体下图标不显示，例如新微软雅黑，能否内置图标
![image](https://github.com/user-attachments/assets/7b29ab70-914d-450b-9c74-b1ff987b9859)
- 如何设置默认中文
- 排序方式我没有搞懂，这是我在面板手动排的序，似乎dash并没有按我的来
![image](https://github.com/user-attachments/assets/f88e2f57-2ed3-46f0-af0d-7a57a460e8b9)

**Comment by hamster1963** [comment]
感谢提出的问题。
3. 面板排序问题，在哪吒面板 v0.18.3 版本后才在API中公开了排序字段，可以尝试更新哪吒面板，当获取到排序字段后，nezhadash会优先根据排序序号进行排序。
https://github.com/naiba/nezha/commit/9d96c58ff91d7b02ce4c43b505f2c11c8f92b82d

**Comment by ssln5014** [comment]
> 感谢提出的问题。 3. 面板排序问题，在哪吒面板 v0.18.3 版本后才在API中公开了排序字段，可以尝试更新哪吒面板，当获取到排序字段后，nezhadash会优先根据排序序号进行排序。 [naiba/nezha@9d96c58](https://github.com/naiba/nezha/commit/9d96c58ff91d7b02ce4c43b505f2c11c8f92b82d)

我的版本
![image](https://github.com/user-attachments/assets/042fb342-7f4c-4e43-b388-85f0083f9579)

**Comment by hamster1963** [comment]
感谢回复，正在针对 -1 排序序号这种情况进行修复。

**Comment by hamster1963** [comment]
关于图标和默认语言的问题，我将会创建新的 issue，后续可以在单独的 issue 中进行讨论，谢谢。

**Comment by ssln5014** [comment]
> 关于图标和默认语言的问题，我将会创建新的 issue，后续可以在单独的 issue 中进行讨论，谢谢。

好的，谢谢回复

**Comment by hamster1963** [comment]
排序问题已在 v0.3.0 版本中修复
https://github.com/hamster1963/nezha-dash/releases/tag/v0.3.0
