### ISSUE TITLE
硬盘显示参数STG忘乘100了

### ISSUE THREAD

**Issue by astych666** [hamster1963/nezha-dash#3]
https://github.com/hamster1963/nezha-dash/blob/652e9ec13728c6495a3130df13846618b719b0e5/app/(main)/ClientComponents/ServerListClient.tsx#L30
这里对比MEM和STG，应该是大佬您忘记乘100了导致最后显示的效果是STG 百分之零点几

**Comment by hamster1963** [comment]
#f28b970787185dd7da7a69731492160a8325f4af

**Comment by hamster1963** [comment]
已修复，感谢🙏
