### ISSUE TITLE
【问题反馈】最新版本列表会不停移位

### ISSUE THREAD

**Issue by ssln5014** [hamster1963/nezha-dash#34]
https://github.com/user-attachments/assets/01c1030d-f40b-4989-b9d3-979c6ea48c19

站点为：[https://x.dsuk.top](https://x.dsuk.top)

**Comment by hamster1963** [comment]
![CleanShot 2024-09-29 at 11  25 13@2x](https://github.com/user-attachments/assets/47bc7deb-c78b-4283-ba0d-9fbc8127ecb8)
看到应该是因为display_index 重复导致的，将 display_index 设置为不重复即可。

**Comment by hamster1963** [comment]
已在 v0.3.2 版本修复
