### ISSUE TITLE
可以添加分组功能吗

### ISSUE THREAD

**Issue by kattocloud** [hamster1963/nezha-dash#37]
如果哪吒面板方面存在分组，dash也可以自动套用哪个分组吗？

**Comment by hamster1963** [comment]
是否类似这种效果？

<img width="591" alt="CleanShot 2024-10-02 at 13 22 34@2x" src="https://github.com/user-attachments/assets/53474735-faf6-48e8-8f6f-ba99007e6fd9">

**Comment by hamster1963** [comment]
谢谢建议，需要考虑一下这个需求对界面的影响程度。

**Comment by hamster1963** [comment]
#38 
![CleanShot 2024-10-02 at 17 51 36@2x](https://github.com/user-attachments/assets/a063b71b-c996-49da-a0d6-bb7178a7abbf)
已实现分组切换
