### ISSUE TITLE
排序似乎不会跟随面板设置？

### ISSUE THREAD

**Issue by JohnsonRan** [hamster1963/nezha-dash#4]
在面板里重新排了下顺序，但是仪表盘里依然是按照添加顺序排序的

**Comment by hamster1963** [comment]
目前通过 API 获取的数据中，没有包含排序的数据，因此可能这个暂时实现不了...

**Comment by hamster1963** [comment]
目前哪吒面板的 ws 做了跨域限制，正在寻找新的方式去获取数据

**Comment by kuusei** [comment]
> 目前哪吒面板的 ws 做了跨域限制，正在寻找新的方式去获取数据

根据我的理解 next server side 并不受跨域限制影响, 但我没试过连哪吒面板的 ws, 可能还有别的限制

**Comment by hamster1963** [comment]
> > 目前哪吒面板的 ws 做了跨域限制，正在寻找新的方式去获取数据
> 
> 
> 
> 根据我的理解 next server side 并不受跨域限制影响, 但我没试过连哪吒面板的 ws, 可能还有别的限制

目前还没尝试过在 server side 去做 websocket 的转发，但已知的是 vercel 的 serverless 环境不支持 websocket，所以可能要转换成 sse 或者其他的形式

**Comment by kuusei** [comment]
> > > 目前哪吒面板的 ws 做了跨域限制，正在寻找新的方式去获取数据
> > 
> > 
> > 根据我的理解 next server side 并不受跨域限制影响, 但我没试过连哪吒面板的 ws, 可能还有别的限制
> 
> 目前还没尝试过在 server side 去做 websocket 的转发，但已知的是 vercel 的 serverless 环境不支持 websocket，所以可能要转换成 sse 或者其他的形式

https://github.com/naiba/nezha/commit/9d96c58ff91d7b02ce4c43b505f2c11c8f92b82d
注意到今天哪吒的更新已经加上 DisplayIndex 了, 似乎暂时没必要考虑 websocket

**Comment by hamster1963** [comment]
> > > > 目前哪吒面板的 ws 做了跨域限制，正在寻找新的方式去获取数据
> > > 
> > > 
> > > 根据我的理解 next server side 并不受跨域限制影响, 但我没试过连哪吒面板的 ws, 可能还有别的限制
> > 
> > 
> > 目前还没尝试过在 server side 去做 websocket 的转发，但已知的是 vercel 的 serverless 环境不支持 websocket，所以可能要转换成 sse 或者其他的形式
> 
> [naiba/nezha@9d96c58](https://github.com/naiba/nezha/commit/9d96c58ff91d7b02ce4c43b505f2c11c8f92b82d) 注意到今天哪吒的更新已经加上 DisplayIndex 了, 似乎暂时没必要考虑 websocket

嗯...我还没更新面板, 看来得做不同的判断

**Comment by hamster1963** [comment]
#12 现在优先根据 DisplayIndex 排序
