### ISSUE TITLE
希望增加自定义网站Logo，名称，简介的功能

### ISSUE THREAD

**Issue by kattocloud** [hamster1963/nezha-dash#40]
通过自行改动也可以实现
不如原生支持的好，建议可以考虑一下，毕竟还牵扯到版本更新的问题
当然这个功能可以收费，比如10块钱解锁这个功能

**Comment by hamster1963** [comment]
首先，这个项目会保证永久开源和免费，不会存在收费的情况。
在自定义这块，由于开源的性质，还是推荐 fork 仓库后再自行进行样式上的修改，不仅仅是这样灵活度更高，也是因为这块功能在目前架构下比较难做，目前没有外部存储，目前可以想到的就是存储在环境变量中，或者还有什么更好的建议？
谢谢🙏
