### ISSUE TITLE
[BUG]布局元素小问题及单位问题

### ISSUE THREAD

**Issue by ssln5014** [hamster1963/nezha-dash#41]
![image](https://github.com/user-attachments/assets/e80a500d-2581-4868-a2e0-93f4696dbc59)
网速过大时会重叠，还有Mb/s似乎不太准确，建议和nz官方一样只用单字母表示表示

**Comment by hamster1963** [comment]
先改用 M/s 的方式进行展示吧，后续看看如何优化。

**Comment by hamster1963** [comment]
[v0.3.11](https://github.com/hamster1963/nezha-dash/releases/tag/v0.3.11)
已修改
