### ISSUE TITLE
新功能：网络监控数据图表

### ISSUE THREAD

**Issue by Ham0mer** [hamster1963/nezha-dash#42]
大佬，你更新的好频繁。
有时间的能否加入tcp ping的监控

**Comment by hamster1963** [comment]
是否有更加具体一些的需求，或者描述？

**Comment by ssln5014** [comment]
> 是否有更加具体一些的需求，或者描述？

他说的大概是[这个](https://nezha.wiki/guide/services#%E7%BD%91%E7%BB%9C%E5%BB%B6%E8%BF%9F%E5%9B%BE%E8%A1%A8:~:text=%E5%A5%BD%E7%9A%84%E8%A7%A6%E5%8F%91%E4%BB%BB%E5%8A%A1%E3%80%82-,%E7%BD%91%E7%BB%9C%E5%BB%B6%E8%BF%9F%E5%9B%BE%E8%A1%A8,%E6%9C%8D%E5%8A%A1%E5%99%A8%E7%9A%84%E5%90%8D%E7%A7%B0%E6%9D%A5%E9%9A%90%E8%97%8F%E6%88%96%E6%98%BE%E7%A4%BA%E5%AF%B9%E5%BA%94%E7%9A%84%E6%95%B0%E6%8D%AE%E3%80%82,-%E7%AE%A1%E7%90%86%E7%9B%91%E6%8E%A7)
但感觉没什么必要，可能要数据库？而且不好排版
（有了更好）

**Comment by hamster1963** [comment]
了解，感谢解惑，已加入待办，可能创建一个新的页面专门进行显示会比较直观。

**Comment by Ham0mer** [comment]
> 了解，感谢解惑，已加入待办，可能创建一个新的页面专门进行显示会比较直观。

刚看见大佬，确实是楼上说的意思，不需要数据库，哪吒提供了这个 API

**Comment by Ham0mer** [comment]
GET /api/v1/monitor/{id}

**Comment by hamster1963** [comment]
了解，加入图表涉及的代码较多，需要一段时间来规划开发一下这个功能。

**Comment by Ham0mer** [comment]
> 了解，加入图表涉及的代码较多，需要一段时间来规划开发一下这个功能。

明白，大佬抽时间整就行，我自己尝试改了一下，太丑了
但是你的审美就符合我的审美😢

**Comment by hamster1963** [comment]
过奖，我也不是大佬😂，都是慢慢磨出来的。

> > 了解，加入图表涉及的代码较多，需要一段时间来规划开发一下这个功能。
> 
> 明白，大佬抽时间整就行，我自己尝试改了一下，太丑了 但是你的审美就符合我的审美😢

**Comment by hamster1963** [comment]
#43 已新增网络监控页面

**Comment by ssln5014** [comment]
> #43 已新增网络监控页面

哥们你这效率也太高了，nb

**Comment by Ham0mer** [comment]
> > #43 已新增网络监控页面
> 
> 哥们你这效率也太高了，nb

大哥中午都没休息

**Comment by hamster1963** [comment]
图表页面在 Vercel 上存在问题，修复中

**Comment by hamster1963** [comment]
https://github.com/hamster1963/nezha-dash/releases/tag/v0.4.1
已修复图表📈，欢迎体验提出意见。

**Comment by Ham0mer** [comment]
> https://github.com/hamster1963/nezha-dash/releases/tag/v0.4.1 已修复图表📈，欢迎体验提出意见。

太帅了，大佬，晚上下班回家更新

**Comment by ssln5014** [comment]
> https://github.com/hamster1963/nezha-dash/releases/tag/v0.4.1 已修复图表📈，欢迎体验提出意见。

似乎有点问题
![image](https://github.com/user-attachments/assets/00b9cb67-f931-47ba-aa7a-a4d4cd141d4d)
![image](https://github.com/user-attachments/assets/d5c2da55-7905-4a56-b880-c7ebe0e26d95)
https://x.dsuk.top/

**Comment by hamster1963** [comment]
稍后进行修复

**Comment by hamster1963** [comment]
![CleanShot 2024-10-09 at 17 10 28@2x](https://github.com/user-attachments/assets/357ecb42-3e62-47de-9506-0a225fa86c38)
已修复

**Comment by yibin** [comment]
请问这个页面的入口在哪里？

**Comment by hamster1963** [comment]
如果您在哪吒面板配置了服务监测，则点击服务器信息即可进入这个页面查看图表。
![CleanShot 2024-10-10 at 14 01 23](https://github.com/user-attachments/assets/c06b90f6-b55e-41bb-b002-312409495500)

**Comment by yibin** [comment]
我是有配置的，在官方默认的面板能看到三网延迟信息。

是不是这个dash有版本要求？我部署在CF上的。

**Comment by hamster1963** [comment]
> 我是有配置的，在官方默认的面板能看到三网延迟信息。
> 
> 是不是这个dash有版本要求？我部署在CF上的。

在你fork的仓库拉取一下cloudflare分支的更新吧😄

**Comment by yibin** [comment]
> > 我是有配置的，在官方默认的面板能看到三网延迟信息。
> > 是不是这个dash有版本要求？我部署在CF上的。
> 
> 在你fork的仓库拉取一下cloudflare分支的更新吧😄

更新一下重新部署就有了 :)

感谢

**Comment by Ham0mer** [comment]
大佬，太高产了一直更新
有个小bug，我把延迟时间改成大于一分钟的就不能连成一条线，下面是90秒的效果
不是大问题，老哥先休息休息
![微信截图_20241010210431](https://github.com/user-attachments/assets/e60e9673-82b9-4bf7-a376-b1b03ee05442)
这个是官方的
![微信截图_20241010210735](https://github.com/user-attachments/assets/0120e201-0f74-4b7f-ab4b-5bf2151efb7a)

**Comment by hamster1963** [comment]
> 大佬，太高产了一直更新
> 
> 有个小bug，我把延迟时间改成大于一分钟的就不能连成一条线，下面是90秒的效果
> 
> 不是大问题，老哥先休息休息
> 
> ![微信截图_20241010210431](https://github.com/user-attachments/assets/e60e9673-82b9-4bf7-a376-b1b03ee05442)
> 
> 这个是官方的
> 
> ![微信截图_20241010210735](https://github.com/user-attachments/assets/0120e201-0f74-4b7f-ab4b-5bf2151efb7a)
> 
> 
> 
> 
方便给我网址看一下吗？ 明早看看

**Comment by Ham0mer** [comment]
> > 大佬，太高产了一直更新
> > 有个小bug，我把延迟时间改成大于一分钟的就不能连成一条线，下面是90秒的效果
> > 不是大问题，老哥先休息休息
> > ![微信截图_20241010210431](https://private-user-images.githubusercontent.com/57058906/375389194-e60e9673-82b9-4bf7-a376-b1b03ee05442.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg1NjYyODAsIm5iZiI6MTcyODU2NTk4MCwicGF0aCI6Ii81NzA1ODkwNi8zNzUzODkxOTQtZTYwZTk2NzMtODJiOS00YmY3LWEzNzYtYjFiMDNlZTA1NDQyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEwVDEzMTMwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNjMGE2NWZkZmQ0Y2JiNDZmNGYxMDg2ZDFhYmI2ZjBiYzIxNGMyM2Q2MmY1NTYzMTg5N2Q2OTQ4MjMxNjhjM2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.oy4D5E5rnLMAiAn9vEDj4neUdzTj96pxtlBvJRHkg1E)
> > 这个是官方的
> > ![微信截图_20241010210735](https://private-user-images.githubusercontent.com/57058906/375389781-0120e201-0f74-4b7f-ab4b-5bf2151efb7a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg1NjYyODAsIm5iZiI6MTcyODU2NTk4MCwicGF0aCI6Ii81NzA1ODkwNi8zNzUzODk3ODEtMDEyMGUyMDEtMGY3NC00YjdmLWFiNGItNWJmMjE1MWVmYjdhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEwVDEzMTMwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU2OTg5MDcxMTQxNDZjYjg1YjZlZDhmMmQwZjhmOWQxMjI0NWZlMzNhYTEyMDgzZWMyZDFiYWQwMzcyYWI4NTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.f4_7O_Q580Kj5V2W8_2LvtbFGhKk0iBXjltQVKV5QBM)
> 
> 方便给我网址看一下吗？ 明早看看

哪吒官方（选择RainYun_HongKong查看）：https://server.dogb.cn/network
nezha-dash：https://nezha-dash-git-main-xuezhelis-projects.vercel.app/en/3

**Comment by hamster1963** [comment]
看了一下好像是因为时间点真的没有数据（丢包，官网好像是拉平来展示的🤔

**Comment by Ham0mer** [comment]
> 看了一下好像是因为时间点真的没有数据（丢包，官网好像是拉平来展示的🤔

不是啥大问题老哥，一般大家都是30s监控，所以一分钟内肯定有数据
我这服务器今天线路炸了，我改了一下
