### ISSUE TITLE
当server监控超过5个时，server页面超出的监控不会显示折线图

### ISSUE THREAD

**Issue by FarEastTZ** [hamster1963/nezha-dash#45]
版本: Docker v0.4.1
第五个会正常显示
![image](https://github.com/user-attachments/assets/45d5640b-4a5e-4c33-b1a1-784abecdccd1)
而到第六个开始就没有折线图显示了
![image](https://github.com/user-attachments/assets/b27d8050-20c3-4af6-b1e6-2d032f9ea570)

**Comment by hamster1963** [comment]
感谢，马上修复

**Comment by FarEastTZ** [comment]
> 感谢，马上修复

辛苦了，请问下server页面手机的排版会做适配吗

**Comment by hamster1963** [comment]
> > 感谢，马上修复
> 
> 辛苦了，请问下server页面手机的排版会做适配吗

应该做了适配了..是说哪一块的适配呢？

**Comment by FarEastTZ** [comment]
> > > 感谢，马上修复
> > 
> > 辛苦了，请问下server页面手机的排版会做适配吗
> 
> 应该做了适配了..是说哪一块的适配呢？

就是监控折线图
![Screenshot_20241009_152134_Chrome.jpg](https://github.com/user-attachments/assets/c9047add-9be1-4c6d-82df-ef298e72558c)

**Comment by hamster1963** [comment]
![image](https://github.com/user-attachments/assets/755b6fcf-13b2-47ec-98d9-058cacb2ee0b)
这么奇怪，请问手机型号是什么？谢谢

**Comment by FarEastTZ** [comment]
> ![image](https://github.com/user-attachments/assets/755b6fcf-13b2-47ec-98d9-058cacb2ee0b)
> 这么奇怪，请问手机型号是什么？谢谢

三星S23
Chrome 129.0.6668.70
Android 13; SM-S9110 Build/TP1A.220624.014

**Comment by hamster1963** [comment]
了解，会和超出无法显示问题一起修复。

**Comment by ssln5014** [comment]
蹭个issue
图表能和官方一样合并吗？或者y坐标量程固定一下，好做对比

**Comment by hamster1963** [comment]
> 蹭个issue 图表能和官方一样合并吗？或者y坐标量程固定一下，好做对比

由于官方的API返回数据结构的问题，需要一个对比时间进行合并的算法，有空再看看吧...

**Comment by hamster1963** [comment]
![CleanShot 2024-10-09 at 17 09 41@2x](https://github.com/user-attachments/assets/0a348068-7aa7-4cd2-ba7e-17c8a3c8a268)
已修复

**Comment by hamster1963** [comment]
> 蹭个issue 图表能和官方一样合并吗？或者y坐标量程固定一下，好做对比

![CleanShot 2024-10-09 at 22 17 28@2x](https://github.com/user-attachments/assets/bc4653f0-3b78-4a0f-aeb0-422c3aaaa638)
已实现，凌晨更新
