### ISSUE TITLE
ping页面不会自动刷新

### ISSUE THREAD

**Issue by ssln5014** [hamster1963/nezha-dash#47]
![1000036439](https://github.com/user-attachments/assets/2d4867fe-e152-485f-a6a8-21b681156c05)
![1000036440](https://github.com/user-attachments/assets/696ca578-766d-408a-b901-21f56ac1b786)
cookie和缓存已经清了，这个页面需要手动刷新才能显示最新的信息

**Comment by hamster1963** [comment]
将会与主页面获取数据时间间隔保持一致

**Comment by hamster1963** [comment]
https://github.com/hamster1963/nezha-dash/releases/tag/v0.5.2
已修复
