### ISSUE TITLE
元素布局有点小问题

### ISSUE THREAD

**Issue by ssln5014** [hamster1963/nezha-dash#49]
![image](https://github.com/user-attachments/assets/5373edb8-c829-440b-9c30-40da089c9dc6)

**Comment by hamster1963** [comment]
<img width="325" alt="CleanShot 2024-10-10 at 15 03 37@2x" src="https://github.com/user-attachments/assets/ead19aaf-56d0-46d8-9867-4a6621000a8c">
如果您说的是y坐标，这是有意为之的😂

**Comment by hamster1963** [comment]
没有其他关于布局问题的话，就先关闭这个Issue了，感谢🙏

**Comment by ssln5014** [comment]
> 没有其他关于布局问题的话，就先关闭这个Issue了，感谢🙏
好的，了解
