### ISSUE TITLE
新功能：服务器核心数据展示流量信息

### ISSUE THREAD

**Issue by yibin** [hamster1963/nezha-dash#50]
这个UI真的是非常清爽！

very nice！！

主页面上要是能把每台vps的网络流量也展示出来就好了，我看API是有返回的，在界面上可否做一些调整，分两行显示，把出入的网络总流量也显示出来呢。

苦于自己看不懂，不然就提PR了 😭

![image](https://telegraph-pic.pages.dev/1728544910543.png)

**Comment by hamster1963** [comment]
![CleanShot 2024-10-10 at 15 23 44@2x](https://github.com/user-attachments/assets/759ab70e-bdc8-4902-89b7-23f5054aaa50)
目前如果您点击名称，会有弹出详情框，不知道这样是否满足您的需求？

**Comment by hamster1963** [comment]
> 这个UI真的是非常清爽！
> 
> very nice！！
> 
> 主页面上要是能把每台vps的网络流量也展示出来就好了，我看API是有返回的，在界面上可否做一些调整，分两行显示，把出入的网络总流量也显示出来呢。
> 
> 苦于自己看不懂，不然就提PR了 😭
> 
> ![image](https://camo.githubusercontent.com/05eb8c7c06fced20c6e0c14d4e51dbdbe23afa9d1cb0f69d0bcb192186a1a3db/68747470733a2f2f74656c6567726170682d7069632e70616765732e6465762f313732383534343931303534332e706e67)

目前这五项是提取了核心的信息进行展示，也比较好进行排版，维持整体页面的稳定，因此很多详情信息放在了弹出框中

**Comment by yibin** [comment]
@hamster1963 

点击悬停，我有尝试过，but还是不如直接在页面上展示直观。

**Comment by hamster1963** [comment]
了解，这个需求对页面影响较大，考虑作为可选项加入

**Comment by yibin** [comment]
感谢～

作为环境变量配置，默认就是当前的页面布局，开启后就是另一种了 😄

**Comment by hamster1963** [comment]
![CleanShot 2024-10-11 at 13 17 36@2x](https://github.com/user-attachments/assets/0698e116-3602-4925-b85f-d5226a02a736)
https://github.com/hamster1963/nezha-dash/releases/tag/v0.5.4
已在 v0.5.4 中实现，相关配置项为NEXT_PUBLIC_ShowNetTransfer

**Comment by yibin** [comment]
@hamster1963 

非常感谢，已更新。

![image](https://telegraph-pic.pages.dev/1728635076156.png)
