### ISSUE TITLE
支持对游客隐藏服务器

### ISSUE THREAD

**Issue by basiczombie-47** [hamster1963/nezha-dash#51]
最近面板更新加的，希望可以跟进。🫡

**Comment by hamster1963** [comment]
了解🫡，将会在近期版本中添加

> 最近面板更新加的，希望可以跟进。🫡

**Comment by hamster1963** [comment]
https://github.com/hamster1963/nezha-dash/releases/tag/v0.5.3
已在 v0.5.3 版本中支持

**Comment by hamster1963** [comment]
已修复，拉取 cloudflare 分支最新代码即可。

**Comment by 1amfine2333** [comment]
我拉了最新的，部署到了pages，还是没有对游客隐藏的服务器

**Comment by hamster1963** [comment]
> 我拉了最新的，部署到了pages，还是没有对游客隐藏的服务器

哪吒面板是否也更新了呢？是最近的版本才加入到 API 的字段

**Comment by 1amfine2333** [comment]
> > 我拉了最新的，部署到了pages，还是没有对游客隐藏的服务器
> 
> 哪吒面板是否也更新了呢？是最近的版本才加入到 API 的字段

我看了下，是最新的
<img width="162" alt="image" src="https://github.com/user-attachments/assets/82bfefa3-94ab-457a-94da-dec85bea8edb">

**Comment by hamster1963** [comment]
> > > 我拉了最新的，部署到了pages，还是没有对游客隐藏的服务器
> > 
> > 
> > 哪吒面板是否也更新了呢？是最近的版本才加入到 API 的字段
> 
> 我看了下，是最新的 <img alt="image" width="162" src="https://private-user-images.githubusercontent.com/24676292/375962142-82bfefa3-94ab-457a-94da-dec85bea8edb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg3NDE2ODAsIm5iZiI6MTcyODc0MTM4MCwicGF0aCI6Ii8yNDY3NjI5Mi8zNzU5NjIxNDItODJiZmVmYTMtOTRhYi00NTdhLTk0ZGEtZGVjODViZWE4ZWRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEyVDEzNTYyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMwNGUyMDNlNWEwNmU2MTIwNzU3NjdkYWM0OTQxYjFhZDAyNDNmZWMxOTkyMzVjYTg2OWI5ZTA4ZjM1ZmY1ZmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.mL_NURFR9EPmYdp_6TEXuWFkxLxxE-o9v4RU_OYiAEg">

方便提供一下地址吗？可以发送到我的邮箱，排查了一下，好像没有找到什么问题。

**Comment by 1amfine2333** [comment]
是要哪吒面板的地址吗？

**Comment by 1amfine2333** [comment]
> > > > 我拉了最新的，部署到了pages，还是没有对游客隐藏的服务器
> > > 
> > > 
> > > 哪吒面板是否也更新了呢？是最近的版本才加入到 API 的字段
> > 
> > 
> > 我看了下，是最新的 <img alt="image" width="162" src="https://private-user-images.githubusercontent.com/24676292/375962142-82bfefa3-94ab-457a-94da-dec85bea8edb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg3NDE2ODAsIm5iZiI6MTcyODc0MTM4MCwicGF0aCI6Ii8yNDY3NjI5Mi8zNzU5NjIxNDItODJiZmVmYTMtOTRhYi00NTdhLTk0ZGEtZGVjODViZWE4ZWRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEyVDEzNTYyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMwNGUyMDNlNWEwNmU2MTIwNzU3NjdkYWM0OTQxYjFhZDAyNDNmZWMxOTkyMzVjYTg2OWI5ZTA4ZjM1ZmY1ZmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.mL_NURFR9EPmYdp_6TEXuWFkxLxxE-o9v4RU_OYiAEg">
> 
> 方便提供一下地址吗？可以发送到我的邮箱，排查了一下，好像没有找到什么问题。

是要哪吒面板的地址吗

**Comment by hamster1963** [comment]
不是，是这个项目部署后的地址

**Comment by 1amfine2333** [comment]
https://4c92d723.nezha-dash-etc.pages.dev/

**Comment by hamster1963** [comment]
🤔，看到页面没有服务器，是没有配置吗？

**Comment by hamster1963** [comment]
现在会隐藏掉在哪吒面板配置了对游客隐藏的服务器，其他没有配置隐藏的会继续显示

**Comment by 1amfine2333** [comment]
emmmm了解了，能改天否加个开关，哈哈哈哈哈哈哈哈哈

**Comment by hamster1963** [comment]
🤔，开个新的issue讨论这个开关吧😂
