### ISSUE TITLE
请问我如何可以展示详情页面的信息呢？

### ISSUE THREAD

**Issue by cigar** [hamster1963/nezha-dash#55]
![CleanShot 2024-10-11 at 10 50 40@2x](https://github.com/user-attachments/assets/48be0dff-41f7-4703-8626-524fd93dd386)
如图这样，如何能像你这样展示里面的信息呢？
我目前是基于Cloudflare上部署了 https://monitor.217178.xyz/zh

**Comment by hamster1963** [comment]
可以拉取一下cloudflare分支最新的代码，会有错误提示。
https://buycoffee.top/blog/tech/nezha-upgrade
这里的代码是获取哪吒面板的监控数据，首先需要在哪吒面板中配置服务监控项目。
https://nezha.wiki/guide/services.html
![CleanShot 2024-10-11 at 10 59 39@2x](https://github.com/user-attachments/assets/f86f465d-c6ff-44bc-a33e-1cc836b651e5)

**Comment by cigar** [comment]
感谢回复，我去探索一下
