### ISSUE TITLE
分组显示问题

### ISSUE THREAD

**Issue by kattocloud** [hamster1963/nezha-dash#57]
之前版本是，不管Nezha的设置里面是否在Nezha的主页显示这个服务器，Nezhadash都是默认显示的。
但是现在是Nezha那边不显示，Nezhadash也不显示了
这个逻辑感觉可以加一条变量把他开关或者和之前一样

**Comment by hamster1963** [comment]
🤔，这是官方新版本的特性，为什么会有那边不显示这边显示的需求呢，可以告诉一下吗？

**Comment by hamster1963** [comment]
已新增ForceShowAllServers强制显示全部服务器变量

> 看到了nezha的更新信息 `修复 dashboard 自定义主题，通过 in https://github.com/naiba/nezha/pull/434 为 api 暴露 HideForGuest` 看起来这个需求还是我的问题，我自己想想办法
