### ISSUE TITLE
服务器监控图表显示不正常

### ISSUE THREAD

**Issue by huyunyadi** [hamster1963/nezha-dash#59]
![image](https://github.com/user-attachments/assets/c300afe2-0c0e-4673-945c-c453dc854034)
但我访问别人的页面显示又是正常的，应该跟客户端环境没有关系，是不是配置问题？
cloudflare部署

**Comment by hamster1963** [comment]
现在汇总页面，是根据时间去分组显示，单独的有连续显示吗？

**Comment by huyunyadi** [comment]
单独的选择显示是正常的

**Comment by hamster1963** [comment]
这个主要是因为根据时间分组的原因，当数据分布不均匀并且间隔比较大的时候就会这样。

**Comment by huyunyadi** [comment]
我本身的服务监测是60秒一次，哪吒默认是30秒，应该跟这个有关系吗？或者是您的时间分组不适配？

**Comment by hamster1963** [comment]
可以提供一下站点进行排查吗？

> 我本身的服务监测是60秒一次，哪吒默认是30秒，应该跟这个有关系吗？或者是您的时间分组不适配？

**Comment by huyunyadi** [comment]
地址已发邮件，麻烦您了！

**Comment by hamster1963** [comment]
收到，感谢提供。

**Comment by hamster1963** [comment]
查看数据后发现间隔不太均匀，一些数据可能是丢包导致的，可以截图官方的对比一下吗，感谢

**Comment by huyunyadi** [comment]
![image](https://github.com/user-attachments/assets/6fe32b1b-6a98-497f-8861-532179da970b)
第一台服务器的

**Comment by hamster1963** [comment]
https://github.com/hamster1963/nezha-dash/commit/a627fa6fb5506c5c733df68f50b49d131a271127
已提交了一个修复，可以拉取cloudflare分支最新代码部署测试一下，期待反馈。

**Comment by hamster1963** [comment]
> ![image](https://private-user-images.githubusercontent.com/26137420/375926342-6fe32b1b-6a98-497f-8861-532179da970b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg3MTU4NDAsIm5iZiI6MTcyODcxNTU0MCwicGF0aCI6Ii8yNjEzNzQyMC8zNzU5MjYzNDItNmZlMzJiMWItNmE5OC00OTdmLTg4NjEtNTMyMTc5ZGE5NzBiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEyVDA2NDU0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcxYjMxZjg0ZTgzNDJkZWU5NjZmZTE3Mzc3YjhjYjUxYTQ4YWUzNTE0YjE4ZjEyNGFhZWU2YjE3YmZlZDk4MjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.tz7Sn0TWzJkpSmJLFT9YNvYYROjAkfT4YCSw6dR2l68) 第一台服务器的

https://github.com/hamster1963/nezha-dash/commit/a627fa6fb5506c5c733df68f50b49d131a271127
已提交了一个修复，可以拉取cloudflare分支最新代码部署测试一下，期待反馈。

**Comment by huyunyadi** [comment]
问题已修复，感谢您的付出！
