### ISSUE TITLE
开个显示"对游客隐藏服务器"的开关

### ISSUE THREAD

**Issue by 1amfine2333** [hamster1963/nezha-dash#60]
开个显示"对游客隐藏服务器"的开关，默认不显示，感谢🙏🙏🙏

_Originally posted by @hamster1963 in https://github.com/hamster1963/nezha-dash/issues/51#issuecomment-2408579614_

**Comment by hamster1963** [comment]
https://github.com/hamster1963/nezha-dash/commit/791ec6097d3ba84fa4430a884c82391035033a03
已新增
