### ISSUE TITLE
离线机器问题及Log和网站说明问题

### ISSUE THREAD

**Issue by kattocloud** [hamster1963/nezha-dash#61]
**1:是否考虑将离线的服务器，只在离线服务器当中显示，或者调整下显示顺序，以下面这个人的面板效果说明：
这样感觉有点残缺的不舒服**
![QQ_1728803124654](https://github.com/user-attachments/assets/83dfd851-5144-4a22-9339-3146e9e71121)

**2：还是建议通过环境变量的方式，修改网站Logo和说明，不知道能否实现。**

**Comment by hamster1963** [comment]
header自定义已实现

**Comment by hamster1963** [comment]
看看如何优化吧，离线这个目前只能从优化卡片的大小来使得视觉上平衡一些

**Comment by hamster1963** [comment]
对齐与离线卡片样式已优化

**Comment by hamster1963** [comment]
> 太赞了，希望你自己搞个赞赏系统，哪怕一杯咖啡呢！！！

感谢您的咖啡☕️，这是我的赞赏页面，收到您的赞美已经很满足😄。
https://buycoffee.top/coffee

**Comment by hamster1963** [comment]
> 50CNY，不成敬意 喝杯咖啡

感谢您的巨款支持，这对我来说是莫大的鼓励，谢谢您😄

**Comment by hamster1963** [comment]
感谢您的支持，没有其他的问题，我就先关闭这个issue了。
