### ISSUE TITLE
Application error: a client-side exception has occurred (see the browser console for more information).

### ISSUE THREAD

**Issue by 52assert** [hamster1963/nezha-dash#62]
想问一下，是不是接口不兼容了![image](https://github.com/user-attachments/assets/f60b812b-02b4-431c-ba9f-7d3a7d77e52c)

**Comment by hamster1963** [comment]
请问已经拉取最新版本了吗？

**Comment by 52assert** [comment]
是的，我是使用docker拉取的镜像，另外我把代码也拉到本地了，发现调用的接口是api/server，现在官方文档好像是没有这个接口的

**Comment by hamster1963** [comment]
<img width="735" alt="CleanShot 2024-10-13 at 15 52 47@2x" src="https://github.com/user-attachments/assets/a51ca6fd-f7e0-4746-8801-7f04c614aaa3">
有的哦，建议排查一下环境变量的问题

**Comment by 52assert** [comment]
详情是有的哈，获取所有是没有的
![image](https://github.com/user-attachments/assets/7546665f-f847-484d-914b-09b9b79592f3)
![image](https://github.com/user-attachments/assets/52cdde90-82ed-4020-af58-cb2dedf8af96)
![image](https://github.com/user-attachments/assets/c93a838b-74a1-4588-8055-6481df757abb)
![image](https://github.com/user-attachments/assets/5ccb5ec5-7217-4241-8162-0cb22fc5b188)
![image](https://github.com/user-attachments/assets/f591f236-1d6f-4c4b-abe5-171f8445729d)
![image](https://github.com/user-attachments/assets/62b8c6a1-f7b2-47f4-b83b-2f544a370b8d)

**Comment by hamster1963** [comment]
<img width="572" alt="CleanShot 2024-10-13 at 16 00 51@2x" src="https://github.com/user-attachments/assets/9de39b90-cec9-4780-bde0-3863fbaaebc3">
我是在服务端获取的，前端获取的是通过nextjs的服务端经过处理后的结果

**Comment by hamster1963** [comment]
https://buycoffee.top/blog/tech/nezha
可以参考架构设计

**Comment by 52assert** [comment]
好的知道了，谢谢，我再看看

**Comment by 52assert** [comment]
解决了，
![image](https://github.com/user-attachments/assets/b93eb533-a740-431e-9039-759f0354418b)
url之前用的https+域名，就不行，应该是请求https出问题了
