### ISSUE TITLE
请问获取网络数据失败，请检查是否开启服务端监控要怎么解决啊

### ISSUE THREAD

**Issue by iStarCc** [hamster1963/nezha-dash#65]
搞了半天也没有成功，能不能指导一下，谢谢
<img width="1100" alt="image" src="https://github.com/user-attachments/assets/5edcbdd4-a5e8-41de-8c61-1be8660e7b69">

**Comment by hamster1963** [comment]
这里获取哪吒面板的监控数据，首先需要在哪吒面板中配置服务监控项目。
https://nezha.wiki/guide/services.html
![CleanShot 2024-10-11 at 10 59 39@2x](https://github.com/user-attachments/assets/f86f465d-c6ff-44bc-a33e-1cc836b651e5)

**Comment by iStarCc** [comment]
是不是要等一段时间有了数据才显示

**Comment by hamster1963** [comment]
同时建议先拉取最新的代码，可以参考https://buycoffee.top/blog/tech/nezha-upgrade

**Comment by hamster1963** [comment]
> 是不是要等一段时间有了数据才显示

在哪吒面板网络面板看到有数据，在这里也就可以获取到数据

**Comment by iStarCc** [comment]
OK，多谢

**Comment by hamster1963** [comment]
好的，如果问题解决可以手动关闭issue
