### ISSUE TITLE
能不能添加一个世界地图功能

### ISSUE THREAD

**Issue by kattocloud** [hamster1963/nezha-dash#67]
可以直观的查看，目前已有的服务器所在的区域，就类似nezha的serverstatus主题右下角的隐藏的地图功能
完全可以把这个地图功能做的更精致一些
![image](https://github.com/user-attachments/assets/68c31586-034a-4ff3-a122-c9407e7581ce)

**Comment by hamster1963** [comment]
我个人还没接触过地图这类的开发，不知是否有大神可以提pr😂
