### ISSUE TITLE
是否可自定义API刷新间隔？

### ISSUE THREAD

**Issue by csa026** [hamster1963/nezha-dash#7]
面板做得不错，美中不足的是数据刷新的间隔太长（约5秒？），是否可自定义API刷新间隔，或者修改代码的那一部分可以更改频率？ 习惯了哪咤面板的2秒一刷新，要等著数据刷新有点难受哈

**Comment by hamster1963** [comment]
感谢提出的意见，我现在进行改进，将刷新间隔移到环境变量中。

（现在刷新间隔较长的原因主要是考虑到 Vercel 平台对于请求的计费问题，因此在服务端做了1 秒的缓存，可能会造成响应上感知延迟的问题）

**Comment by hamster1963** [comment]
#9  已增加获取数据间隔环境变量
NEXT_PUBLIC_NezhaFetchInterval

**Comment by hamster1963** [comment]
> 面板做得不错，美中不足的是数据刷新的间隔太长（约5秒？），是否可自定义API刷新间隔，或者修改代码的那一部分可以更改频率？ 习惯了哪咤面板的2秒一刷新，要等著数据刷新有点难受哈

#9 已增加获取数据间隔环境变量
NEXT_PUBLIC_NezhaFetchInterval
