### ISSUE TITLE
总流量可否显示上下行

### ISSUE THREAD

**Issue by ssln5014** [hamster1963/nezha-dash#70]
只显示上行不太直观
![image](https://github.com/user-attachments/assets/016c45f1-2876-4eb9-bbc0-285374504d8a)
![image](https://github.com/user-attachments/assets/c780f1ef-3c8d-4e3d-9802-bb36bcd6f91b)

**Comment by hamster1963** [comment]
了解，尝试优化一下

**Comment by hamster1963** [comment]
https://github.com/hamster1963/nezha-dash/releases/tag/v0.6.0
已在 v0.6.0版本中实现
