### ISSUE TITLE
关于服务器详情的建议

### ISSUE THREAD

**Issue by kattocloud** [hamster1963/nezha-dash#72]
1. 将详情加一个小的标识，因为如果第一次使用的人话，可能不会发现在这个功能
2. 是否可以将服务器详情和网络详情合并到一个里面？
3. 见仁见智哈，请仓鼠收集下其他人的意见之后，再做决定

**Comment by hamster1963** [comment]
1. 这个一直想做，但是没想到特别好的提示的方式，我去找找灵感。
2. 分开页面主要是数据量和功能分割的问题：
- 如果合并到一个页面，数据包大小有点大，对于Vercel部署的数据传输这块的计费会大许多。
- 网络详情页面，有一些用户没有在面板开启监控服务，因此合并到一起的话可能对这部分用户的页面影响较大。

**Comment by hamster1963** [comment]
> **网络详情页面是否可以集成到一个页面用标签来切换？就像homedash那样做一个标签？或者目前的分组？** 综合考虑吧，我觉得已经很完善了，再重新优化下提示方式，详情页合并这个问题，保持现状也没问题，刚刚又在论坛强烈推荐一波你的项目，受到了大家的一致好评！

这个建议非常不错，近期优化一下！

**Comment by hamster1963** [comment]
现在去修

**Comment by hamster1963** [comment]
> 已赞赏，买杯奶茶！！

感谢赞赏，已修复，关于合并页面我会重新创建一个issue，这个就先关闭。
