### ISSUE TITLE
有没有可能加一个最近网速图

### ISSUE THREAD

**Issue by ssln5014** [hamster1963/nezha-dash#73]
与https://github.com/hamster1963/nezha-dash/issues/72 整合一下，记录最近5分钟或十分钟的网速变化，原版缺失这个功能

**Comment by hamster1963** [comment]
问题是现在没有外部存储，我怎么记录😂

**Comment by ssln5014** [comment]
> 问题是现在没有外部存储，我怎么记录😂

也是，想想用外部数据库不太合适，那关issues了
