### ISSUE TITLE
希望能支持歷史圖表數據

### ISSUE THREAD

**Issue by Mowd** [hamster1963/nezha-dash#75]
目前只有實時圖表，希望未來能夠紀錄歷史數據

**Comment by hamster1963** [comment]
目前沒有外部存儲，可能比較難實現..

**Comment by Mowd** [comment]
或許可以考慮使用sqlite實現這樣的需求

**Comment by hamster1963** [comment]
瞭解，但部署在vercel和cloudflare這種serverless無法使用sqlite

**Comment by hamster1963** [comment]
目前API无法获取历史数据，此需求暂无法实现
