### ISSUE TITLE
支持查看密码

### ISSUE THREAD

**Issue by jason5ng32** [hamster1963/nezha-dash#76]
是否有可能考虑支持哪吒监控本身的查看密码，当前台隐藏所有或部分服务器的时候，可以通过查看密码进行展示？

**Comment by hamster1963** [comment]
受限于目前通过API无法获取到这个数据，此功能较难实现，但可以考虑引入密码

**Comment by jason5ng32** [comment]
可能可以考虑环境变量里直接定义一个前台密码？目前我用 nginx 来做验证，略微显得不优雅

**Comment by hamster1963** [comment]
已加入待办

**Comment by hamster1963** [comment]
正在构建中

**Comment by hamster1963** [comment]
<img width="1194" alt="CleanShot 2024-10-21 at 10 40 43@2x" src="https://github.com/user-attachments/assets/971ed882-8367-4aaf-a6ff-d6995369f388">
已在 v0.6.4版本中实现
