### ISSUE TITLE
服务器详细界面不显示国期

### ISSUE THREAD

**Issue by linlxh** [hamster1963/nezha-dash#83]
![image](https://github.com/user-attachments/assets/22ff2b1c-8f69-476f-8a37-6327f6a4bbf3)

**Comment by hamster1963** [comment]
将会增加在下方的地区显示中。

**Comment by linlxh** [comment]
🆗👍

**Comment by hamster1963** [comment]
https://github.com/hamster1963/nezha-dash/commit/b3168750b34f7ad003ff7e3afccbd1929c78c4c5
已实现
