### ISSUE TITLE
最新的repo我在cloudflare上尝试部署了2次都失败了

### ISSUE THREAD

**Issue by cigar** [hamster1963/nezha-dash#85]
不知何故，我在自己的分支上更新了最新的代码，然后CF上去重新部署还是失败！附件是我的Log，还望帮我看看，谢谢
[nezha-dash.5796d95e-8fe3-4794-8b87-76132d0ebb23.log](https://github.com/user-attachments/files/17469750/nezha-dash.5796d95e-8fe3-4794-8b87-76132d0ebb23.log)

**Comment by hamster1963** [comment]
需要使用cloudflare分支，才可以在cf pages进行部署

**Comment by hamster1963** [comment]
https://buycoffee.top/blog/tech/nezha-cloudflare 您可以参考教程，在cf部署时所需的配置项都在文章内

**Comment by cigar** [comment]
搞定，谢谢咯
