### ISSUE TITLE
几个小建议

### ISSUE THREAD

**Issue by zhdsmy** [hamster1963/nezha-dash#87]
首先，目前已经非常好用了，感谢开发！！！

有几个小的建议，希望可以纳入考虑

1. 
![Snipaste_2024-10-22_16-34-28](https://github.com/user-attachments/assets/522eae27-f8eb-43dd-94d0-cfcd22afb833)

2. 
![Snipaste_2024-10-22_16-35-46](https://github.com/user-attachments/assets/6695517a-f0fb-4225-b815-92bd5ca867e6)

3. 
![Snipaste_2024-10-22_16-37-47](https://github.com/user-attachments/assets/e5154e06-6e1c-4d42-86f1-c7ab5ea2ed19)

**Comment by hamster1963** [comment]
正在优化监控页面排版

**Comment by hamster1963** [comment]
https://github.com/hamster1963/nezha-dash/releases/tag/v0.7.0
已在 v0.7.0完成上述全部优化

**Comment by zhdsmy** [comment]
@hamster1963 感谢如此迅速的支持，已请咖啡，还有两个小建议，可以考虑一下

![image](https://github.com/user-attachments/assets/4675668f-59a5-4250-85c8-0745c357e35a)

**Comment by hamster1963** [comment]
感谢赞赏，出差回来就看看🐶

**Comment by hamster1963** [comment]
https://github.com/hamster1963/nezha-dash/releases/tag/v0.7.1
已在v0.7.1版本中完成优化，并且改进了跳转详情页面的性能。
