### ISSUE TITLE
能不能给个超链接功能

### ISSUE THREAD

**Issue by kattocloud** [hamster1963/nezha-dash#94]
右上角给1-2个标签，作为超级链接，启用和具体的超级链接可以用环境变量的方式实现！
我想把Uptimekuma的网页和它集合在一起，不知道是否有这个必要性？？？

**Comment by hamster1963** [comment]
目前先暂时停止新功能的加入，您可以邀请我进入您的仓库为您修改

**Comment by hamster1963** [comment]
不会的，可以选择合并在一起

**Comment by hamster1963** [comment]
已提交
<img width="1513" alt="CleanShot 2024-10-25 at 01 16 29@2x" src="https://github.com/user-attachments/assets/fb35fde5-323d-4396-8545-ff925ae15de7">

环境变量格式为：
NEXT_PUBLIC_Links=[{"link":"https://baidu.com","name":"Baidu"},{"link":"https://google.com","name":"Google"}]
