### ISSUE TITLE
详情页面的问题

### ISSUE THREAD

**Issue by ssln5014** [hamster1963/nezha-dash#95]
这个详情将来会做新的子页吗？
如果只有详情和网络页的话个人感觉没有必要做切换，单页观感会更好，一目了然
![image](https://github.com/user-attachments/assets/5ac238e5-bdf0-4a29-9fb0-b82fa449463d)
![image](https://github.com/user-attachments/assets/ffbe0291-5bd9-47c6-8c51-10470be500ea)

**Comment by hamster1963** [comment]
https://github.com/hamster1963/nezha-dash/issues/72#issuecomment-2423967249
可参考这个 issue，有关新功能，请关注后续的哪吒官方。

**Comment by ssln5014** [comment]
> [#72 (comment)](https://github.com/hamster1963/nezha-dash/issues/72#issuecomment-2423967249) 可参考这个 issue，有关新功能，请关注后续的哪吒官方。

好的好的，没有看到
