### ISSUE TITLE
服务器名称显示问题

### ISSUE THREAD

**Issue by kattocloud** [hamster1963/nezha-dash#99]
仓鼠大佬：
对于服务名称的显示来说，如果有一些名称过长，他们自动换行，这个问题在电脑端出现，手机端没问题
举例说明
![image](https://github.com/user-attachments/assets/5a2d2af5-141e-453a-a21f-7866d6a62f8b)
有没有办法优化一下，比如把他的宽度调整为20个字节，有一些服务器可能名称确实不是很好标
换行后也比较割裂，强迫症很难受！！

**Comment by hamster1963** [comment]
对于太长的名称，做成光标移动到名称后滚动的是否观感更好？

**Comment by hamster1963** [comment]
已重构服务器名称

**Comment by zhdsmy** [comment]
@hamster1963 

> 已重构服务器名称

目前的服务器名称显示方案强迫症表示更加不能接受了，想了几种方式供参考：

1、名称区域稍微长一点，然后自动滚动，像跑马灯一样；
2、国旗加名称放在 CPU / 内存 这些的上面，这样名称的长度就够够的了；（横向多出来的空间可以后续为套餐信息等预留）

毕竟萝卜青菜各有所爱，所以看能不能做成环境变量提供多种方案可选

**Comment by hamster1963** [comment]
> @hamster1963
> 
> > 已重构服务器名称
> 
> 目前的服务器名称显示方案强迫症表示更加不能接受了，想了几种方式供参考：
> 
> 1、名称区域稍微长一点，然后自动滚动，像跑马灯一样； 2、国旗加名称放在 CPU / 内存 这些的上面，这样名称的长度就够够的了；（横向多出来的空间可以后续为套餐信息等预留）
> 
> 毕竟萝卜青菜各有所爱，所以看能不能做成环境变量提供多种方案可选

感谢建议，计划将方案2的显示加入到环境变量中，全局将名称在卡片上方显示。

**Comment by hamster1963** [comment]
> > 已重构服务器名称
> 
> 感谢，已赞赏

感谢🙏，您太客气了

**Comment by hamster1963** [comment]
> ![image](https://private-user-images.githubusercontent.com/121779192/382656236-730c640e-7698-413f-9cd8-baedf1f80c57.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA3MDA4NjUsIm5iZiI6MTczMDcwMDU2NSwicGF0aCI6Ii8xMjE3NzkxOTIvMzgyNjU2MjM2LTczMGM2NDBlLTc2OTgtNDEzZi05Y2Q4LWJhZWRmMWY4MGM1Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwNFQwNjA5MjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xODI1ZTc1ZjA4ZmE4MjQ3NzFiOWJjZGJmNzM5NWQyMDBjZmZjNzE2ZGFlODM5ZGEyZTMyYzdmOTFmOWI4YzYwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.QrfVSGb-jEOYxpfL0wzcNjX0WsDv6YXfmyl3SAlbDNc) 其实向手机端横屏后的这个效果就可以了

了解，将会把这个作为环境变量，回退之前的重构代码。

**Comment by hamster1963** [comment]
现在，服务器名称显示宽度已增加，如需固定名称在卡片顶部显示，设置环境变量 NEXT_PUBLIC_FixedTopServerName 为true即可。
<img width="1582" alt="CleanShot 2024-11-04 at 14 50 06@2x" src="https://github.com/user-attachments/assets/84508a47-df0f-4f35-999f-9fdfaf0a44d6">

**Comment by hamster1963** [comment]
<img width="1094" alt="CleanShot 2024-11-04 at 21 45 37@2x" src="https://github.com/user-attachments/assets/bed140c5-f5e6-42c2-b05b-965cf9aa609d">
已增加参数显示
